### ISSUE TITLE
Bookmarking pages in Reader View (Firefox)

### ISSUE THREAD

**Issue by Majdoddin** [aaFn/Bookmark-search-plus-2#104]
In Firefox, you can  brows a webpage in [Reader View](https://support.mozilla.org/en-US/kb/firefox-reader-view-clutter-free-web-pages).

Trying to bookmark a page in Reader View, something is created, but if you click on it later nothing happens. If you right-click it, the context menu is not like that of a bookmark.

Moreover, it is not possible to mouse-drag the tab of the page to a bookmarks folder to create a Bookmark.

If Reader-View is turned off, everything is fine again.

Not sure if it is a bug of this addon or a bug of Firefox.

**Comment by aaFn** [comment]
Hello @Majdoddin , it might be that the drag operation has a different format.
Could you point me at a page which has a reader view, so that I try and verify ?

**Comment by Majdoddin** [comment]
Hello,
There are many, like Wikipedia articles, e.g https://en.wikipedia.org/wiki/Book

**Comment by aaFn** [comment]
Ok, I see, such URL's are of the form "about:reader...", and "about:" URL's are not allowed for add-ons, they generate a security exception error when the add-on is trying to use them (i.e. to open them in a tab).

Anyway, I will modify BSP2 to accept creating such bookmarks, this is not forbidden, and to have context menus work on them also (for now, they are seen as protected bookmarks by BSP2, because of the "about:" in them).

**Comment by Majdoddin** [comment]
I think the important thing is to be able to bookmark the original url, without the "about:reader..." part. 
Because, how you want to "view" the page does not have to be specified in the bookmark. For example, one can also change the font-size when viewing a page (by ctrl-+-), but that should have no effect when he then bookmarks the page.

I had opened 6 pages about a subject and wanted to bookmark them in a folder, but I noticed that just five is bookmarked (one was in Reader View), and that happened without a warning. This should be avoided.

**Comment by aaFn** [comment]
I would tend to agree with you, however the "about:reader..." piece is added by the native FF functions themselves like Ctrl-D, or with drag & drop to the native FF bookmark sidebar.

Which means I can in BSP2 remove the "about:reader..." piece and store only what is after the "?", but:
- this will be effective only for things directly dragged to it
- it will be inconsistent with the native FF behavior
- it won't act on actions like dragging to the native bookmark sidebar, or like Ctrl-D ... because BSP2 is not involved in them, it is only notified of things created by other means, so that it displays them.

What do you think ?

**Comment by Majdoddin** [comment]
On Fennec, by bookmarking a page in View Mode, the _original_ url is saved, that is _without_ ""about:reader..."", but at the same time, it is saved offline.
This is done by [Reading List](https://support.mozilla.org/en-US/kb/save-web-pages-your-reading-list-firefox-android), an [addon](https://addons.mozilla.org/en-US/firefox/addon/reading_list/), that seems to be by default installed on Fennec.

it is decided  [here](https://bugzilla-dev.allizom.org/show_bug.cgi?id=938247), people discuss it later [here](https://bugzilla-dev.allizom.org/show_bug.cgi?id=938247).

May be it is worthwhile to see why they do differently on PC, but unfortunately I cannot invest more time in it.

**Comment by aaFn** [comment]
After investigation, I am adding the function, but it's a bit of a hack because FF tabs Webextension API doesn't allow to retrieve tabs in Reader mode ...

Indeed, they are in the "about:reader?url=<encodedURIComponent>" form, and this is not accepted by the pattern matching function of the tabs API:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/query

I found a way to get the corresopnding tab, however such tabs have a special favicon as it seems, corresponding to the "about:reader.." form, and not the original one .. 

So decided for simplicity to keep the "about:reader..." form in the created bookmark, like standard FF bookmark sidebar does, rather than trying to reconstruct the original URL and then fetch the original favicon ...

**Comment by aaFn** [comment]
@Majdoddin , 2.0.61 is out now .. let me know if any problem

**Comment by aaFn** [comment]
Closing as it's been 1 month, I guess all is working fine.
Let me know if not.
Thank you, aaFn.
