### ISSUE TITLE
Does not work on mobile FF

### ISSUE THREAD

**Issue by sparrowek** [aaFn/Bookmark-search-plus-2#109]
After installing the plugin on mobile phone I cannot use it - I do not know how or it just does not work.

**Comment by aaFn** [comment]
I am even surprised you could install it on your mobile phone, the add-on is only published for Windows, Linux and MacOS. Not for android.

**Comment by aaFn** [comment]
Mmmh something is strange, I see on the Developer Hub that in spite of my settings, this is shown for all platforms. Something is going wrong on the Firefox publication platform :-(

**Comment by aaFn** [comment]
I checked again, the add-on is not pblished on the add-on site for FF Android = https://addons.mozilla.org/en-US/android/

You have been able to install it because you have been pointing your FF Android to the Firefox normal add-on address.
This is a known bug of AMO, cf.
https://discourse.mozilla.org/t/disabling-add-on-on-the-firefox-for-andoid/37859
and
https://github.com/mozilla/addons-frontend/issues/6136

You should use the right site, and all will be fine (until Mozilla sanitizes things so that Android FF going to firefox add-on site is immediately redirected to the proper Android site).

Closing as there's nothing I can do = dependency for Mozilla to improve things
