### ISSUE TITLE
Feature Request: Add "Parent Folder" as a column option when doing bookmark searches

### ISSUE THREAD

**Issue by catgil3** [aaFn/Bookmark-search-plus-2#117]
Hi, This request may be better as a whole separate addon, so apologies if this request goes too far outside the scope of the current addon. 

My request is for a Parent Folder column option when doing bookmark searches. (see image)

When I am doing a bookmark search I'd like to identify the parent folder of each of the results. It could help me locate other files I've overlooked in folders I've not considered during my search, or to clean up scattered files by identifying redundant folders in different locations. 

Thanks for considering. 
Cat
Image of search column options:
![screenshot of bookmark search](https://user-images.githubusercontent.com/30908709/67028247-f7a68b80-f0d8-11e9-9c49-6aa91455179b.png)

**Comment by aaFn** [comment]
Hello @catgil3, you are talking of the Bookmark Library obviously.
Add-ons cannot modify the Library anymore. That was possible in the past, but no more since FF57.

The only thing I was able to do, and it is already in current version since some time, is that you can right click on any bookmark, and in the context menu, you will find a "BSP2 Path to bookmark item" submenu. If you remain on it or click on it, you will see the full path to the bookmark item.

If you have ticker the setting "Reverse folder hierarchy in paths" in BSP2 options page, you will see the parent folder first in that path ... else it is the last one.

Note that this context menu works not only in the Bookmarks Library, but also in the Bookmarks menu in FF, or i nthe Bookmarks toolbar, or also in the native bookmarks sidebar.

This is as far as I could get for now, hope this helps.

**Comment by aaFn** [comment]
Closing as dependent on FF to enable this.
Will reopen to add the function if FF provides support for it.
Thank you, aaFn.
