### ISSUE TITLE
Browser crash while using BSP2

### ISSUE THREAD

**Issue by NicolasWeb** [aaFn/Bookmark-search-plus-2#12]
Using BSP2 2.0.4, I experience browser crash.
Here is the crash trace I got to investigate : [FF+BSP2_crash_1.txt](https://gist.github.com/NicolasWeb/a0af8116b2fa6ccdc2043db9f01f616a).
It's related to BSP2, as it happen after a search, but might comes from my FF profile who knows...

**Comment by aaFn** [comment]
Ah, not sure how to exploit that trace, there's nothing I see which tells where it crashed or what FF was really doing at the moment it crashed .. However, I am not used to FF crash traces. Are there tools to look at it in details and to interpret it better than just looking at it with our eyes ?

**Comment by aaFn** [comment]
I found a memory leak due to URL object which needs to be revoked after it has been  instantiated with "new URL (xx)", in favicon retrieval background process (worker).

This is not very well documented in the MDN, and many examples using new URL in the MDN don't do it.

However this is explained in:
- https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL
- https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL

This could get to very high amounts of memory on initial load of the add-on when all bookmarks require favicon retrieval, and crash FF.

It is probable that this is related to that issue as this is the only case I could find / experiment.

The memory leak is corrected in 2.0.10, therefore I am closing the issue.

In case of new crashes, I am not really sure of what to take nor how.
I only know of that https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Reporting_a_Performance_Problem, but this is while FF is still running ..
