### ISSUE TITLE
Feature request: lite version

### ISSUE THREAD

**Issue by eleius** [aaFn/Bookmark-search-plus-2#122]
Would you please consider creating an alternative, "light" version of your addon, that only adds the "path to bookmark item" menu to the native Bookmarks UI ?

As much as I like your work, this feature is the only thing I actually need and have been missing since the days of Opera 12 (also, no extra code for custom bookmark management = lower cpu/memory usage in my Firefox with its ~20 active addons.)

**Comment by aaFn** [comment]
Hello @eleius, there is already an easy way to do that now:
- Since sidebar code do not run when not displayed, simply display the native FF bookmark sidebar, or any other sidebar you want, or none .. and then you are sure that this piece of BSP2 won't consume anything (neither memory, neither CPU).
- In the background task, which I would need to keep anyway in a Lite version, there is only one thing which regularly consumes CPU = this is favicon fetching (each time you create a new bookmark or change one)
=> disable it in the options page
- Then hide the BSP2 star from the toolbar. It doesn't consume anything, but this is more in spirit with your Lite approach

That should do it. The background task will do very minimum activity to keep track of the tree and so of paths whenever something changes in the bookmarks.

**Comment by eleius** [comment]
Good to know, thanks :)

**Comment by eleius** [comment]
about:performance shows 1.6 MB used by BSP2 but at least no cpu impact, which seems a good compromise.

**Comment by aaFn** [comment]
Good. If you order by bigger used memory first, you should see it near the bottom of the list then.
Many web pages consume more than that :-)
So you're good.
