### ISSUE TITLE
Ghost bookmarks under "Other Bookmarks" are not erasable

### ISSUE THREAD

**Issue by ghost** [aaFn/Bookmark-search-plus-2#127]
I have 2 bookmarks under the Other Bookmarks category. These 2 bookmarks only show up when using Bookmark search plus 2; they do not show up under the default Firefox Bookmarks > Show All Bookmarks viewer. I cannot delete these ghost bookmarks from Bookmark search plus 2. I cannot even move them. However, I can confirm the bookmarks were real; I did bookmark them at some point in the past. Unfortunately, they are somehow just stuck now.

**Comment by aaFn** [comment]
Hello @darknessenvelops , when you right click on them, what are the available actions ?
From your description, it looks like they are seen as "protected".
For those kind of bookmarks, there are very little actions available in the context menu (around 4 or so only), so that would be the best way to tell if that is the case.

Else, it could be that there is a desynchronization with the FF database (i.e. they were deleted elsewhere and FF never notified BSP2 ..). In that case, do a "Reload from FF API" in the options page.

Let me know.

**Comment by darknessenvelops** [comment]
Thanks! It was the second option. I didn't know BSP2 had to synchronize with the FF database manually. I've enabled the option "Revert to old behavior of loading full bookmark tree from Firefox API at each restart". This should solve future problems, right?

I actually edited my bookmarks with BSP2 before I knew it was working with a stale copy. I wonder how much information I lost due to the BSP2 database not being in sync with the Firefox database, if any?

**Comment by aaFn** [comment]
Well, normally this is not needed. However FF seems to have developed a few bugs on that since FF60 where they introduced new format for saving things .. and so I had to develop that button in the options page to let people re-synchronize.

I am now developing something in next version (2.0.71) so that:
1.  BSP2 can auto-detect as much de-synchronization as possible (which is not 100%, unfortunately), and to trigger an auto-reload as early as possible
2. BSP2 registers all actions in an history, and later on will provide an interface to come back in past or to replay things as needed. See #75

**Comment by aaFn** [comment]
2.0.71 is out with the function of auto-detecting some of the de-synchronization cases, and then provoking the reload, as early as possible.

That should avoid a number of cases where people have to press the "Reload from FF API" button in the options page.

Closing the issue as things are resolved on your side, and the additional feature should do it for people. thanks, aaFn.
