### ISSUE TITLE
Include full path for folders in upper search result view

### ISSUE THREAD

**Issue by ejemba** [aaFn/Bookmark-search-plus-2#129]
Hi @aaFn ,

Can you add an option to display full path folder in upper search result view. 

For instance I have multiple occurences of 'java' folders
- java
- java
- java
- java8
- java 

Something like could be more usefull

- References > Java
- References > emacs > Java
- Flux > java
- References > Java> Java8
- Old > Barre Personelle > java 

As an option (or not it did not break anything) it will remove an additional click to disambiguate which java directory I'm in. 

This only for folder for my use case.

What do you think ?

**Comment by aaFn** [comment]
Hello @ejemba , you mean display the full path at front of the folder, or inside the folder name ?
Hard to do as this would introduce specific code for displaying bookmarks (this is the same in both the search pane and in the bookmarks pane).

Did you notice that by right clicking on the item, (bookmark or folder), you can display its properties and that the properties window contains the full path ?

**Comment by ejemba** [comment]
hi @aaFn , sorry I did not understand «inside the folder name ». 

What I want is  replacing "Java" in the search result pane which is the relative name by "References > emacs > java" the full name.

Or at least proportionnaly if you can indent, to reflect the depth

I noticed that the right click give me the information but this break the flow.
For my example I would click 5 times.

**Comment by aaFn** [comment]
Ok, so the search result pane is now a flat list. It has been at a very ancient past something with indentation, but that was impractical as things were hidden on right when too deep.
Similarly, showing the full path is pushing the name to the right, hiding it. Or adding the path behind would quickly also be impractical, as soon as the path is long enough to go too much on right ...

The only thing I can think of is maybe to use the mouse hover, which is not limited to the sidebar boundaries. Currently, this is showing the bookmark title and the URL ...:
- maybe add the path also inside it ..? Although this would start to make a lot of information inside, removing readbility
- or maybe only dispay the path when hovering with a modifier key pressed, like "Alt" ..? Although a bit akward and unnatural

**Comment by ejemba** [comment]
In fact, my screen is 3840x2160 so that is why, really, I won't have any problem of depth. I'm sure I'm not the only one with high resolution :) 

You can just provide an option to let those with big screen to have the display I ask ? And by default leave as it is :)

**Comment by aaFn** [comment]
Sorry, too complex as this would make the objects different, as I said each item is a bookmark with a Title in the text field and a URL. Having some with not just the title but a full path in them would make non standard processing. Plus be careful that whatever your resolution, the sidebar has a limit in width which is quite small, imposed by FF ..

Another way could be to activate the "BSP2 path to bookmark item" in the context menu, as it is already activated on the toolbar and in the bookmark menu. The information would be one click away plus a hover on the submenu ..

Or need to think more ..

**Comment by ejemba** [comment]
Perhaps prefix bookmark with the initials + the tooltip

- R.. > Java
- R.. > e.. > Java
- F.. > java
- R.. > J..> Java8
- O.. > B.. > java

**Comment by aaFn** [comment]
Still making things non uniform on bookmarks structure (name + url).
However here is a simple idea:

- Add an option (default = false to remain as normal) to replace title+URL contents in the "tooltip" balloon appearing on hover, by the path content, for search results.

Therefore no click, just remain on the result for about 1s with the mouse, and the path will appear.
User choice, reversible, no impact on bookmark object in the list to avoid side effects.

How would that sound ?

**Comment by ejemba** [comment]
@aaFn I take this one :) 
It remains practicable for my use case.
Thank you for designing the solution

**Comment by aaFn** [comment]
Ok, done deal then. Will be in 2.0.73

**Comment by aaFn** [comment]
Done, 2.0.73 is out now, with the option and feature.
Let me know if any problem.

**Comment by ejemba** [comment]
@aaFn Thank you for your reactivity and your listening.
It works as expected and it is completely useful !

**Comment by aaFn** [comment]
Cool, closing the issue then :-)
Thanks, aaFn.

**Comment by shoulders** [comment]
I love this plugin but I do struggle with the flat search structure because I have many links that I am trying to sort all with the word **InnoDB** and the bookmarks as I process them are removed but are all over the place.

I have just enabled the hover option and am trying it out.

This feature works well but one option I don't think was considered:

Search Result Handling
1. **Normal Search:** Use search as normal. results will appear in the top box in a flat results structure.
2. **Filter the Main Tree:** The main nested bookmarks tree (bottom Window) will get filtered and only matching Bookmarks in their tree will appear.
3. **Both:** Show results in both windows.

Perhaps this can be done without a lot of deep work and thats why I mentioned this approach, just incase. Search results are flat for audience 1, and the Main tree is already nested for Audience 2. 😄 

I thought it was better to add to this relevant issue but I can open a new one if valid.

**Comment by aaFn** [comment]
Hello @shoulders , I presume 1) is the current mode correct ? (i.e., when you click on a result in the flat structure, it goes to the place where the bookmark is in the tree structure)

2) is the Opera way of doing it in the past. They stopped that. Not sure why, but yes, in the case of BSP2, that would be significant work.

3) I am not sure I understand .. what is the difference with 1) ?

**Comment by shoulders** [comment]
hi @aaFn 

- yes option 1 is the normal/current way
- option 2 - I assumed, that because the main bookmarks tree already had the tree logic and layout code that filtering these 'results' would of been an easy thing (i.e.. filter the blob of bookmarks before passing them to the tree rendering code.)
- option 3 - This was just my OCD (crazyness) where you would have the search results displayed as normal in the top box as flat result and then the bookmarks tree at the bottom would be filtered with the search results at the same time.

**Comment by aaFn** [comment]
Ok, thank you for the quick answer. Problem with 2) is that for speed of rendering purposes in FF sidebar, this is not the way things work. Also, such a view would need a way to distinguish from the real view, to avoid confusion (like it was in Opera at the time). Additionally, such a view breaks the flow for dragging & dropping things next to where the result is (that is one of the purposes of BSP2 = show where a search result is to be able to mark new things next to it).
All of that would require some special code.
