### ISSUE TITLE
Directory copying and pasting does not work in text mode (eg text-only mail)

### ISSUE THREAD

**Issue by liar666** [aaFn/Bookmark-search-plus-2#131]
Hi,

First, BIG kudos for the plugin, it saved my life multiple times, be it for searching for a directory and not a simple bookmark, or getting the parent directory of a bookmark. A shame this is not the default behaviour of the integrated Firefox tool!!!

As for my issue:

Context: As a true paranoid (OpenBD user), I read&write emails in plain text only in Thunderbird.

In firefox, with the default "bookmarks" pane (CTRL+c), if I select a directory and right-click, then "copy" (or use CTRL-c), then when I paste (CTRL+v) in an opened email draft, the list of URLs from the directory is pasted in text mode, with directories titles and indentation to mimic the structure in my bookmarks.

Unfortunately in your addon, if I copy in a text mode window (again, plain text only email), nothing happens (or the last copied text is pasted!). I've tested pasting in a HTML email. It works... So the copying part of the code in your app seems to be lacking something.

Would be great if your addon could have the same behaviour as the default FF tool in this case! 

Thanks!

**Comment by aaFn** [comment]
Hello @liar666,

> Context: As a true paranoid (OpenBD user), I read&write emails in plain text only in Thunderbird.

Yes, I do the same .. :-)

I never noticed we could do a Ctrl-C on the native sidebar, interesting.
Should be easy to add I guess.

Now, did you notice that you can drag & drop a bookmark from the BSP2 sidebar (or from the native sidebar also, for that matter), and that it will copy the URL in your text window ?
That should already help you a bit.

And then I see that dragging and dropping a folder does also exactly what you describe in the native sidebar, but in BSP2 I didn't catch that and then it copies the work "fodler" .. not very useful :-D

I will see how to add support for dragging folders in the way it is supported by the native sidebar, and then add Ctrl-C support which is just a key shortcut for the same thing ..

--------------------------------
Side notes:
- are you sure there is indentation in text mode ? When I try here, I get no indentation
- in HTML, clearly there is indentation, and URLs are seen as links, while folders are just text (and separators are HTML lines, while in text they are "--------------------"
- HTML drag & drop is no better with BSP2
- I need not only to implement Ctrl-C and to complement drag & drop, for both text and HTML, but I need to complement the Copy (or Cut I presume) operation for the same behavior
- I also need to add support for dragging & dropping, and copying, separators .. for completeness

**Comment by aaFn** [comment]
Hello @liar666, after investigation, Firefox doen't support yet complex clipboard access for add-ons :-(
See https://developer.mozilla.org/en-US/docs/Web/API/Clipboard
we need access to the full read() and write() methods to be able to have multiform contents (moz bookmark, HTML,, plain text .. etc ...), and this is not yet the case.

All I would be able to do at this stage is to store a plain text string ... = not much useful as this should cover only a few cases, and most of all not yet worth the investment in the code.

Happily, since the Drag & Drop API is (nearly) fully functional, I could extend with all that I listed above.

So to do what you want, you will have to Drag & Drop folders or bookmarks to your Thunderbird mail composition window, and the operation will select and paste the proper form corresponding to the mode it is in:
- if HTML mode composition, it will paste the HTML part from the multi-form datatransfer object
- if text mode composition, it will paste the plain text part from the multi-form datatransfer object
- ...

This extended support will be in 2.0.75, to be out this week-end.

And we'll have to wait that the FF Clipboard API is better supported / more mature to be able to use Ctrl-C and Ctrl-V, or the copy/paste actions in context menus. A bit strange in my eyes since these are more basic and common actions .. but this is how the FF team chose to enable and support things, so we have to do with what we have.

Hope this is ok, aaFn.

**Comment by liar666** [comment]
Hi,

Thanks a lot for all this research.

Indeed, in text mode, the pasted text is not indented (this is some useful feature you could add :) ).

Whatever is possible/easiest for you. If there is only the drag&drop possibility I don't care as soon as I can paste my bookmarks :)

Thanks again for this top tool!

**Comment by aaFn** [comment]
Yes, drag & drop only for now, with text indentation improvement, this is much more readable :-)
Code is done and tested, will be published tonight in 2.0.75

**Comment by aaFn** [comment]
2.0.75 is out now. Let me know if all ok.

**Comment by aaFn** [comment]
Closing the issue as resolved.
Thank you, aaFn.
