### ISSUE TITLE
Where is the latest source code?

### ISSUE THREAD

**Issue by Gitoffthelawn** [aaFn/Bookmark-search-plus-2#133]
The source code in this repo does not appear to reflect the current release on AMO.  Where is the current source code?

**Comment by aaFn** [comment]
Hello @Gitoffthelawn, latest version is always in the add-on itself = Javascript is an interpreted language, and the source code is fully commented and readable.
I only update the source code here from time to time.

**Comment by Gitoffthelawn** [comment]
@aaFn I just want to politely mention that I'm not super thrilled about the code on GitHub not being current.  Of course, it's not the end of the world, as it's always available directly in the xpi on AMO.

I think perhaps, maybe, you could work towards keeping the source code current on GitHub, or add a note in this repo's README.md that the code on GitHub may not reflect the code available on AMO.

**Comment by aaFn** [comment]
Hello @Gitoffthelawn , yes I can already add that, you are correct => done.

I am using Eclipse and I didn't integrate it with Gitxxx, I find git very convoluted in its terms, its procedures and its commands as a source code management system. I have known much better in the past, so I am not thrilled 😁 at it, and do not desire so far to invest much in it.
I simply use GitHub because this is still a free common place many people use nowadays, and because git has the core functions of what a source code management tool should have, but I find it to be the product of a somewhat tortured mind (sorry mister Torvald ..), so I guess I am waiting for a better SCM to be happy with it.

Therefore for now, the upload is manual, and I do it when I have the time, my apologies for the inconvenience.
This is not a definite situation. We'll see if my view and appreciation of git improves with time .. (note:  of course, if we were on a compiled language, I would make it a duty to publish things up to date).

Happy to listen to and evaluate other views and advices, of course.

**Comment by Gitoffthelawn** [comment]
@aaFn Thanks for your note.

I tend to agree.  I'm not a big fan of git, and I've had to invest a fair amount of time to make reasonable sense of it.  Like you, I find its model somewhat tortured and convoluted.  I *still* have "how the heck do I perform this simple task" moments with it.

It's gained so much traction (largely due to GitHub), however, that I foresee it being the standard in the near-term.  Like you, I prefer that wasn't the situation.

One thing I've come to do is to simply cut and paste source code into GitHub.  After I did it once or twice, it became quick and foolproof.  If a repo only has 5 or 6 source files with frequent changes, it can be done in under 3 minutes per version.  You can even write a macro to do it, but I personally like keeping a close eye on things more than allowing macros to run amuck. 

That's my only big tip.  I share your frustrations with git, so I definitely understand and empathize with where you are coming from! :smile:

**Comment by aaFn** [comment]
Right, if can develop some quickly executed routine gesture to do that, I will increase my frequency of uploads. I will think about it, thanks for the suggestion.

**Comment by Gitoffthelawn** [comment]
@aaFn You're welcome.  Take care!
