### ISSUE TITLE
bookmark title in place editing 

### ISSUE THREAD

**Issue by eseb63** [aaFn/Bookmark-search-plus-2#136]
hello, 
would it possible to implement a quick mode to edit the bookmark title (without having to open the properties dialog box, but directly in the treeview) ?
i often use drag and drop from the address bar to create the bookmarks but i often have to edit the default title and opening the properties window is a bit long.
i thought to get similar behavior that the search pane : entering in edit mode if clicking outside the title and icon, and opening the bookmark if clicking on title/icon ?
or entering in edit mode if simple click, and opening if double click (or the opposite)?
thanks for this great work

**Comment by aaFn** [comment]
Hello @eseb63 , I checked how to do that, but the HTML property to realize that is
- unpredictable = for example, if an <enter> is keyed in or pasted in, it introduces a break line, and this requires additional code to handle all possible interpretable cases like also tabs .. etc ... (https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/contentEditable)
- it is based on a feature which is obsolete and discouraged by FF = https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand, with no replacement

To make things simple, I can propose the following to accelerate the process instead:
- When a drag and drop is made while for example pressing the "Alt" key, then BSP2 will immediately launch the properties window for you, so that you can edit its content

avoiding you to have to right click and then click on Properties (much like on the "New bookmark.." or "New folder.." contextual actions).

How does that sound ?

**Comment by eseb63** [comment]
Hello @aaFn ,

too bad, in place editing would have been handy when creating a new bookmark with drag and drop, or changing the title of an existing bookmark too.

your suggestion could be a good workaround for the first case. 

other consideration : for a deeply nested treeview (like mine), building the complete path of the bookmark might be time consuming isn't it (recursive reading of the ancestors) ? and this information is not necessarily useful for everyone or everytime : by example, if using "new bookmark" we know where we want to create it, if just editing title, we don't need  the path etc ...

if so, this path could be displayed only on demand, by example by clicking on a button "path" in the properties dialog box. A global option might also give the choice : always display, or on demand.

this way, the properties box might open quicklier, while keeping all information ? what do you think about ?

**Comment by aaFn** [comment]
Agree that inline editing would be handy. I checked more, I would need to replace on demand an temporarily the HTML element by an input element of size varying with its content ..,
This would be more complex progamming => I might do it one day, but not now.

So for now I will do the Alt thing ..

The path display is very fast, this is not the piece which slows down the property window. The part which is very slow is that because of API restrictions, and inconsistencies across OS'es:
- This is a new browser window in fact, without menu and other things => that is very slow
- I have to open it with a default size and placement decided by FF / the OS, and then I have to resize it and move it .. :-( .. => that is again slowing down its availability.

**Comment by aaFn** [comment]
Closing, as the Alt shortcut for opening editing title on drag and drop was made available in 2.0.76.
Thanks, aaFn.
