### ISSUE TITLE
Tags and keywords in bookmark properties

### ISSUE THREAD

**Issue by calchilo** [aaFn/Bookmark-search-plus-2#145]
New to this add-on.  Question/Comment:  
1.  I use FF tags a lot to organize. Does BMSP2 search FF tags and keywords? They to not show up when I right-click on properties for the url.  If you do not use those fields, I would request you consider adding that feature.  If you do, how do I see/edit tags and keywords?  
2. I see that multiple search text separated by blanks is an "AND" search.  I also see that an "OR" search is possible using the regex vertical bar.  For me, it would be much more useful to have the option of AND or OR in the drop-down magnifier glass icon menu so that blanks separation could be either AND or OR.

**Comment by aaFn** [comment]
Hello @calchilo, unfortunately, since Firefox 57, add-ons can only be Web Extensions, and it is not possible for them to see nor to manipulate Firefox tags and keywords.

See this https://bugzilla.mozilla.org/show_bug.cgi?id=1225916, and the limitations described in BSP2 page https://addons.mozilla.org/en-US/firefox/addon/bookmark-search-plus-2/.

On the space in searches, you are correct, BSP2 is following what the native Bookmark sidebar is doing, and is using a standard FF API for the bookmark search, where ' ' is a AND. This is why I introduced regex as an alternative, to be able to have much more complex search features. Well, this is a '|' instead of a ' ', but at least this is explicit :-)

**Comment by Gitoffthelawn** [comment]
@calchilo I don't know if Mozilla cares, but you can vote for https://bugzilla.mozilla.org/show_bug.cgi?id=1225916

**Comment by aaFn** [comment]
Closing the bug as dependency on Firefox to give us the feature.
Thank you, aaFn.
