### ISSUE TITLE
Feature Request: Scrollbar Colours

### ISSUE THREAD

**Issue by scottfurry** [aaFn/Bookmark-search-plus-2#153]
I finally found the setting to have the bookmark pane follow the FF theme/colouring. This vastly improves the utility of the add-on (no more annoying, blinding white). However, there is one aspect to the theme that is not being picked up. The vertical/horizontal scrollbars for the bookmark side pane are not being styled in a manner consistent with FF theme. In my case with a dark theme, this produces a side pine with light grey on light grey scroll bars. Very difficult to use.

I would like to request a feature change where the theme is applied not just to the display pane background/foreground but also the pane scroll bars. Is this possible?

**Comment by aaFn** [comment]
Hello @scottfurry, indeed that would be great, but this is not supported (yet I guess) by the FF theme API https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme

so I cannot find what is set on the FF main theme for scrollbar colors, and apply them to the sidebar.

(general msg: if anybody sees a way I don't, let me know)

**Comment by scottfurry** [comment]
I want to have hope. I don't know enough of the FF internals to make a suggestion. Although I have vague idea of where to look for the info.

I recently encountered another area where the theme is not being pulled in - dialog window. When I right-click a bookmark and select properties, an un-themed dialog window is being displayed. There has to be a way to get the current FF theme and apply those pieces consistently elsewhere.

**Comment by aaFn** [comment]
Yes, on the property windows, this is me, I didn't apply any theme there, as I can tell from my memory (I am on the road, I do not have the whole code in mind). I didn't find it really useful there so far, so just left the defaults. If that is really worth it, I can look at aligning that window also with he theme.

However, I confirm, there's nothing I can find on scrollbars, this is not accessible through the API. I guess the best I could do is to give a manual way for the user to set the color he/she wants, but I cannot retrieve it from the theme as far as I can see.

**Comment by scottfurry** [comment]
Some Google-Fu of the Mozilla API docs...
[theme.getCurrent](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/theme/getCurrent)
[theme API update](https://blog.mozilla.org/addons/2018/03/08/theme-api-update/)

fingers-crossed this helps.

**Comment by aaFn** [comment]
Yes, this is what I use. It returns a Theme object, which is the link I sent 4 posts above.
In there, nothing about scrollbars, the API does not return information about them.
I checked on other posts in fora on the same subject, they all confirm the API does not include scrollbars information for now :-(

**Comment by scottfurry** [comment]
I misunderstood earlier post and missed the link. Apologies.
I'm out of my depth on this one.

**Comment by aaFn** [comment]
No problem, I believe the best I can do for now is to add an option for the user to override the default color with the one he/she wants (I need to check how to do that, but I believe this is possible through some easy CSS attributes).

Let me know if that would work for you as a workaround.

Thanks, aaFn.

**Comment by scottfurry** [comment]
I tried to dig into this a little myself.
Locally for me, the "Midnight Lizard" add-on allows to set toolbar settings. It helps and saves me from employing techniques that other pages suggest (such as found in the r/FIreFoxCSS subreddit).
Seems mozilla has decided to follow the w3c scrollbar css api (other browsers use different standard).
Dynamic Scrollbars (> FF72) is another story. I can see why they went that way, but... PITA.

**Comment by aaFn** [comment]
Hello @scottfurry, researching a bit more, I found that Firefox has now dynamix colors on scrollbars based on the background color, since FF 72.
See https://www.ghacks.net/2019/11/11/firefox-72-dynamic-scrollbars-based-on-page-color/

However, that was not applying to BSP2 .. so far.

So I investigated ... and discovered that (not exactly sure why):
- changing only the `<body>` or `<html>` background color in BSP2 had no effect on the dynamic scrollbar color
- but changing both to the same value does trigger the effect !!

So far I was applying the background color only to the `<body>`.

I will then apply it to both the `<body>` and `<html>`, and that will be my answer to this issue, as my tests show that it works quite well = with a dark theme, the scrollbar color changes dynamically to more appropriate colors. They are decided by FF, but at least they are consistent with the rest of the FF UI, and supposed to be nicer 😀.

This will be in 2.0.81.
Note: I consider this is a BSP2 bug as it should naturally behave like FF decides, so I am qualifying that issue as `Bug`.

Thanks, aaFn.

**Comment by aaFn** [comment]
2.0.81 is out now, let me know if you can verify and if that improves things for you or not.
Thanks, aaFn.

**Comment by scottfurry** [comment]
Selecting and De-Selecting the "Match FF Theme" produces better appearance of the scroll bars.
I think you nailed it! \o/

Thank you!

**Comment by aaFn** [comment]
Thank you @scottfurry for your quick feedback.
Ok closing the issue now, thank you for reporting, aaFn.
