### ISSUE TITLE
Option to not search until search button clicked. Or the Enter key

### ISSUE THREAD

**Issue by Twistyness** [aaFn/Bookmark-search-plus-2#157]
I have over 20 years of bookmarks. A zillion bookmarks. So the addon will sometimes lock up as I enter characters of a word to search for. Because it restarts the search after each character is entered. So I often can't see what characters I am entering until later on after the search is done. And since I sometimes make spelling errors I have to start over. 

I suggest an option to only do a search when I click the Enter key. Or an option to show a search button.

**Comment by aaFn** [comment]
Currently there is a timeout of 0.5s which is reset each time a key is typed. When this timeout expires, the search is launched if there is 1 or more character(s) in the search box.
This is mimicking what is done on the native bookmark sidebar in Firefox.

So:
- typing characters faster than 2 strokes per second keeps from launching the search
- after timeout, the search is launched as said above (if there is 1 or more characters in the search box)
- once the search is launched, depending on the number of bookmarks and Firefox speed (standard search is a call to the Firefox API), it can indeed take some time ...
- once a search is finished, results are displayed and it is possible to remove / add characters, with the same timeout system

I could add an option to change the timeout for bigger values, for when people are slower on keyboard, so that they can adjust it to adapt things to their own rhythm. How does that sound ?

**Comment by Twistyness** [comment]
Sometimes I am fast, and sometimes I am slow. Is there no way to disable the beginning of search until I take some kind of action? An option to click the enter key might be easier to implement since it doesn't require setting up a search button icon.

**Comment by aaFn** [comment]
I'll see if the HTML input object can have a specific behavior on enter ley, not sure, but I will tell you

**Comment by aaFn** [comment]
Good news, there is no event but I can still catch the <enter> key and verify it is in the search box.
So I will add an option to only act on <enter> key. This will be in 2.0.83.

**Comment by Twistyness** [comment]
Great! Thanks.

**Comment by aaFn** [comment]
Also adding an "Enter" icon for the button at end of the search box, so that there are now two possiblities to execute the search:
- when pressing `<enter>`
- or when clicking on the button (same effect as the `<enter>` key)

**Comment by andreygursky** [comment]
Ideally the searching would be performed asynchronously not blocking the input field UI. If some character is entered, the current search process is canceled and a new one is started. I'd say it is a typical behavior of a well designed UI program. Does Firefox Add-on API allow to implement this?

**Comment by aaFn** [comment]
Hello @andreygursky , the search on FF API is asynchronous (it returns a Javascript Promise), but it cannot be cancelled.
Worse, it can eat up a lot of CPU on its own (one thread basically means up to one core), because it is not very well coded and the SQL data structure is mixing bookmarks, tags .. all together, making SQL queries a bit complex and particularly inefficient as I could see it.
Net is that to avoid problem, I do not launch the search until there is timeout on the input, or until the user presses enter with coming 2.0.83. And once a search is launched, we have to wait it is complete before doing another one, even of the results are to be discarded because we updated the search string :cry:

**Comment by andreygursky** [comment]
> ... but it cannot be cancelled. Worse, it can eat up a lot of CPU on its own (one thread basically means up to one core) for long durations, ...

Sad.

> or until the user presses enter with coming 2.0.83.

Then it is a very useful workaround. Thank you, @aaFn!

**Comment by aaFn** [comment]
2.0.83 is out now with the modifications.
Thanks, aaFn.

**Comment by Twistyness** [comment]
It is working great! Near instant searches when I press the search button, or enter key. 

True for regex searches too. I was trying to find bookmarks and folders about "US Mobile". I have difficulty remembering what to add on both sides of the phrase search though.

**Comment by aaFn** [comment]
Good 😀 . Closing the issue then. Thank you, aaFn.
