### ISSUE TITLE
Display entire Bookmark path when in standard Bookmarks sidebar view

### ISSUE THREAD

**Issue by AJS44** [aaFn/Bookmark-search-plus-2#160]
When using the standard Firefox Bookmarks view and a Search filter is being applied, it is very nice to see that Bookmark Search Plus 2 displays the Bookmark path.  Thank you!

However, quite often the actual Bookmark path is much longer than the displayed portion, so comparing the various listed bookmarks folder locations is challenging. 

If possible, please provide a wider or longer display field that shows the entire path; or perhaps a pop-up mouse-over info balloon to show the entire path.

![BSP2 Bookmark path display](https://user-images.githubusercontent.com/35783664/95368323-981e2e80-089b-11eb-8343-64b90b4ba856.jpg)

Thank you for the BSP2 Extension and keep up your great work!

**Comment by aaFn** [comment]
Hello @AJS44 , in the BSP2 options page, there is an option to reverse the displayed path to start from the selected object, so that truncation does not occur at the end, if that can help.

Problem is that the menu length is not controllable by the add-on, this is Firefox interface choice.
And no we can't display a bubble on a menu.

Now, I guess what I could do is that when clicking on the shown path, maybe a BSP2 property window of the bookmark could be opened, to show the bookmark full path, name and URL.
I would need to check if this is possible => let me know if that could be an answer to your demand.

**Comment by AJS44** [comment]
Thank you for the suggestion to try the reverse-folder-hierarchy option.  It definitely helped to give another clue to the folder locations, but often revealed only approx. the bottom 2-1/2 folder names string out of the sometimes 8 folders depth.  

It would be great if you could investigate the possibility for displaying the full bookmark path in a popup Properties window.  Thank you!

**Comment by aaFn** [comment]
Added the display of BSP2 Properties window when clicking on the path, so that if it is too long, you can then see it fully in its own window.
This can also be a shortcut to get to the BSP2 properties window, as well.

This is in 2.0.84, published today, so closing the issue. Thanks, aaFn.
