### ISSUE TITLE
Feature Request: Drag & Drop of MULTIPLE bookmarks (or folder) outside to Windows Explorer

### ISSUE THREAD

**Issue by pstein** [aaFn/Bookmark-search-plus-2#163]
As you know it is in current Firefox only possible to drag & drop ONE bookmark at a time outside to Windows Explorer.

However sometimes I want to drag multiple bookmarks (even hundred) of bookmarks at once.
Or I want to drag a whole (nested) folder outside to Windows Explorer

This is currently not possible with default bookmark Manager.
And (as far I can seen) not with Bookmark Search plus 2.

Can this feature be added in the next release?

Thank you

**Comment by aaFn** [comment]
Hello @pstein , are you sure you can currently drag and drop URL shortcuts between Windows explorer (or Desktop) and BSP2 ?
I certainly didn't build the support for that so far, and it is not working on my side 😀 

It works on MAC (basically, no titile is transferred, only the URL), half-way only in Linux (received by the desktop as text, but not working from desktop to BSP2), and not in Windows .. so far.

Also, there is a flaw indeed in the FF native bookmark sidebar, if you try to drag several bookmarks to the Windows explorer, it ends up as only one with messed name ...

I will try to add first support for drag & drop with one bookmark.
Then when #29 is ok, I will see if it is possible to support multiple bookmarks drag & drop with the desktop, I am not sure, there is a limitation since FF 71 that its drag & drop API does not support anymore multiple bookmarks, cf. https://developer.mozilla.org/en-US/docs/Web/API/DataTransfer/mozSetDataAt

**Comment by pstein** [comment]
Ok, I have to be more precisely:
I am talking about dragging bookmarks from standard built-in Bookmark Manager/Sidebar and not from BSP2

>Also, there is a flaw indeed in the FF native bookmark sidebar, if you try to drag several bookmarks to the 
> Windows explorer, it ends up as only one with messed name ...

....Thats what I am talking about

>I will try to add first support for drag & drop with one bookmark.
>Then when #29 is ok, I will see if it is possible to support multiple bookmarks drag & drop with the desktop

That would be great

>I am not sure, there is a limitation since FF 71 that its drag & drop API does not support anymore multiple bookmarks, 

Hmm, possibly a dirty workaround with performing x single bookmarks dragging operations for 1 user multi-drag would work.
Any trick is welcomed :-)

**Comment by aaFn** [comment]
I tried all workarounds I could, but could not find any. The multi bookmark drag, as well as the multi-tab drag, is not working anymore in Firefox since FF 71, and decomposing is not possible, we do not "send" drops, they have to come with the mouse pointer => only 1 can come with it now, no more.

So yes, you can drag one by one already today between BSP2 and native FF sidebar or FF bookmark manager, but not anymore multiple bookmarks.

For Windows explorer, I am investigating how to add that, and since it seems based on files from what I can see so far, there might be a way to have multiple ones ... we'll see.

**Comment by aaFn** [comment]
Some good news:
- I confirm this is based on files when receiving from Windows Explorer, so I am introducing support to receive multiple URL shortcuts from there
- I am also introducing support to drag & drop a bookmark to Windows Explorer, however this is not based on files, so I can only send one. At least that will always be something 😀 
- Side point = I found a workaround to reintroduce multi-tabs drag support to the bookmark pane, using alternate features specific to tabs ..

Still can't find a way to do multi-bookmarks drag to FF native bookmarks sidebar, or to Windows Explorer as said above, this is not supported anymore as of FF 71+ 😢 .

This should be all in 2.0.84

**Comment by pstein** [comment]
Ok, thank you.

However I am confused. If you found a way to drag 1 (!) bookmarks outside from Firefox to WindowsExplorer then it should be possible to perform INTERNALLY a multi-drag as well. Just split the list of bookmarks to drag into single operations like in the following pseudo code:

```
set listofbookmarks = .....

while (listofbookmarks not empty) {
  nextsinglebookmark = listofbookmarks[0];
  savebookmarkinwindowsexplorer(nextsinglebookmark);
  listofbookmarks.delete(nextsinglebookmark);
```

That should do the trick.

Any problems with that?

**Comment by aaFn** [comment]
As said above:
- We attach the dragged object(s) to the mouse pointer, it is not a send / save to
- The system expects things in a particular MIME format, which is "text/x-moz-place"
- The FF API does not support anymore to attach more than one object of this type to the mouse pointer.
- The system receives the object(s) attached to the mouse pointer that the user manipulates, and then saves them where the user is placing his mouse pointer to drop to.
Not only we do not know where this is, but also add-ons are not authorized to access the filesystem to write to it, or that would be a serious security breach !

So only one bookmark can be sent to Windows Explorer for now.

I found it was possible to RECEIVE multiple bookmarks from Windows Explorer, because it is using a different MIME type in that direction, based on files, and it is still possible to get multiple files attached to the mouse pointer in the API. Not sure how standard this is by the way, it doesn't seem to be the case all the time in Linux (and couldn't check in MacOS).

On FF tabs, I found that there is a specific property in tabs API which a priori allows me to retrieve what was initially selected, so although I receive only 1 tab from FF, I am using the trick to see what is selected (highlighted), and I ignore what comes from the API, I take the list of selected tabs instead, assuming (maybe wrongly, time will tell) this corresponds exactly to what was dragged and dropped.

**Comment by aaFn** [comment]
2.0.84 is out with capability to drag ONE bookmark to Windows, Linux or MacOs desktop and file manager, and to receive MULTIPLE bookmarks from them, by drag & drop.

I will continue to search if there can be a workaround to drag multiple bookmarks from BSP2 to those environments, so leaving that issue open until I can conclude.

Thanks, aaFn.

**Comment by pstein** [comment]
Thank you.

**Comment by aaFn** [comment]
So I checked again, and didn't find a good way today, sorry.
Clipboard write is not even possible yet, as workaround https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

We need more capabilities from FF API to do that.
Therefore I am closing that for now, as external dependency on FF to supply someting (or until somebody else gives me a workaround / a method that works).

Thanks aaFn.
