### ISSUE TITLE
Show path of bookmark in tooltip?

### ISSUE THREAD

**Issue by mzso** [aaFn/Bookmark-search-plus-2#164]
Hi!

Yesterday I saw the path of bookmarks shown in a tooltip in the library window when hovering a search item. But right I don't.
Since nothing else is relevant, it could only have been this addon. When does it appear?

Can't it be done for the FF bookmark sidebar as well?

**Comment by aaFn** [comment]
Hello @mzso , there is an option `On mouse hover above search result, show path to bookmark item instead of title + url` that you can activate in BSP2 options page, to show the bookmark items path on search results in tooltips, instead fo title+url.

For the native FF bookmark sidebar, FF Bookmark Toolbar, FF Bookmarks menu, FF Bookmarks Library:
- it is not possible for any tooltips on FF native objects, add-ons (like BSP2) cannot do that
- but there is a BSP2-added "Bookmark path" sub-menu in the context menu (right click) on those objects, which shows the bookmark path

**Comment by mzso** [comment]
[**@aaFn**](https://github.com/aaFn) commented on [2020. nov. 22. 19:36 CET](https://github.com/aaFn/Bookmark-search-plus-2/issues/164#issuecomment-731808819 "2020-11-22T18:36:32Z - Replied by Github Reply Comments"):
> Hello [@mzso](https://github.com/mzso) , there is an option `On mouse hover above search result, show path to bookmark item instead of title + url` that you can activate in BSP2 options page, to show the bookmark items path on search results in tooltips, instead fo title+url.
> 
> For the native FF bookmark sidebar, FF Bookmark Toolbar, FF Bookmarks menu, FF Bookmarks Library:
> 
> *   it is not possible for any tooltips on FF native objects, add-ons (like BSP2) cannot do that
> *   but there is a BSP2-added "Bookmark path" sub-menu in the context menu (right click) on those objects, which shows the bookmark path

I guess I misremembered and conflated stuff. Thanks for the explanation.

**Comment by aaFn** [comment]
Ok, closing the issue as the question has an answer 😀 , thank you
