### ISSUE TITLE
open native Bookmark Manager in a tab - via a BSP2 menu item

### ISSUE THREAD

**Issue by shoulders** [aaFn/Bookmark-search-plus-2#172]
This a feature that I thought was lost and I have just found it.

This article hints at it being change in an earlier version
- https://support.mozilla.org/en-US/questions/1264741

`chrome://browser/content/places/places.xul` is now `chrome://browser/content/places/.xhtml`

I was not sure if you knew about this (probably) or if it is something you wanted to include. I thought I would mention it here for reference as the least and give you the option.

thank

shoulders

**Comment by aaFn** [comment]
Yes, many things can be open this way I understand (just need to retrieve the proper URL, see below ..).

Unfortunately, add-ons cannot open / access such URLs = they generate a security error when they trying to open them, and are blocked

Try the following to see what I mean:
- Open a new blank page and copy one of the links below in the address bar, press enter
- You will see the corresponding content open in the tab
- Drag the tab into BSP2 tree = it will create a new bookmark with corresponding name and address at the place where you dropped it
- Open the browser console = Ctrl+Shit+J and empty it (trash bin icon)
- Click on the bookmark you just opened, from BSP2 = a security error will appear in the consolse
-  Click on it from the native FF bookmark sidebar = it will open properly.

```
Bookmark Library       chrome://browser/content/places/places.xhtml
Bookmarks              chrome://browser/content/places/bookmarksSidebar.xhtml
History                chrome://browser/content/places/historySidebar.xhtml
```

**Comment by Gitoffthelawn** [comment]
I like and appreciate @shoulders' desired functionality, and I concur with @aaFn's findings.

I think there is a workaround in Firefox where you can change/add a couple `about:config` settings to allow extensions to do this.  It's been a while since I've researched with this issue, and so I'm not sure of every detail for the current Firefox release.

IOW, I think it's possible to tweak/add settings to make this work, but they are not the defaults.  There are also security/privacy implications to consider if anyone attempts this.

**Comment by aaFn** [comment]
I believe this is what you are referring to:
http://kb.mozillazine.org/Links_to_local_pages_don%27t_work
http://kb.mozillazine.org/Security_Policies

So setting these 3 values should allow local file access:
```
string capability.policy.localfilelinks.checkloaduri.enabled: allAccess
string capability.policy.localfilelinks.sites: *
string capability.policy.policynames: localfilelinks
```
as shown in https://www.quick-tutorials.com/local-link-in-firefox

and presuming this applies also to chrome:// URLS (that I am not sure ... because such URL patterns might not be allowed at all from add-ons and I didn't see any option for changing that !), that would solve the problem.

Note: may need also to set
`"security.fileuri.strict_origin_policy" to "false"`
( I didn't check).

---------------------------------------------
For any person who would enable this, then no need for BSP2 to provide menu items for that:
- simply create the 3 bookmarks I listed above
- and click on them at any time to open the corresponding functions in a tab (in same tab, or new tab, or new window, or even in new private window I guess)

Those settings should also allow BSP2 to open file:/// bookmarks again **(or any other add-on to access local files for that matter, based on "*" on the sites key, so be careful)**

---------------------------------------------
At any rate, I wouldn't advise anybody does that, unless knowing what they do.

It would be much preferrable that FF creates some GUI options on the add-on management page(s) to allow add-ons, one by one, to access local file URLs, like this for Chrome if I understand well https://developer.chrome.com/docs/extensions/reference/extension/#method-isAllowedFileSchemeAccess (assuming again this can cover chrome:// URLs)

See also this for further considerations on the subject: https://wiki.mozilla.org/WebExtensions/Filesystem

**Comment by Gitoffthelawn** [comment]
Yes, that's the basic idea.  I vaguely recall different settings, and using about:config (prefs.js/user.js), but the same basic idea.  It's been many months (maybe even a couple years) since I researched it though!

> It would be much preferable that FF creates some GUI options on the add-on management page(s) to allow add-ons, one by one, to access local file URLs...

This!  Yes, that would be much better.

All the details you put together are quite helpful, and I'm bookmarking this thread for future reference.  Thanks!

**Comment by aaFn** [comment]
Closing the issue as external dependency as I can't do something on it at that time.
Will reopen when / if Firefox allows access to local URLs, and if the demand is not properly addressed by simply authorizing the add-on for such URLs, requiring something more from BSP2.
Thank you, aaFn.

**Comment by Gitoffthelawn** [comment]
Sounds good.

Personally, I prefer to leave unresolved issues open, but with a tag indicating there's nothing you can do right now (which you did when you added the `external-dependency` tag).

You're now my second friend to choose to close such an issue (and tag it) instead of leaving it open.  The other issue was for a different project.  Out of my interest in understand different people's preferences, I'm interested in learning why you prefer to close an unresolved issue?

**Comment by aaFn** [comment]
Indeed, this a choice, and in my case this is related to a limitation of Git and GitHub = only 2 states for an issue, open or closed.
However, I would need here at least a 3rd state, like "pending" or "dependency", or "future" .. In short anything like a wait list.

Why ?
Because I am using the list of open issues as my public work list that I need to planify and manage. And things on wait list are just things I keep in a corner but do not have to act on, so I do not want them to clutter my work list. When they become active because their dependency is resolved, then they come back to my work list.

So two choices as you express:
1. Keep them as open, but with a special flag
2. Make them closed, but with a special flag

I prefer 2) because I can more easily track my progress and manage what is the volume of remaining active things, than if I have to do some filtering to get that view (filters are a bit painful in GitHub). Also then people with the default view (no filter) can clearly see what is my public stack of active things 😀

**Comment by Gitoffthelawn** [comment]
Well explained!  Thank you!
