### ISSUE TITLE
Feature request: New option to open folder AND (!) webpage with ONE click on a result item?

### ISSUE THREAD

**Issue by pstein** [aaFn/Bookmark-search-plus-2#173]
When I open the "Bookmark-search-plus" pane on the left and enter a search pattern, then all the matching bookmarks are shown in the upper result list pane.
Now users have to click on a certain result line to open the corresponding folder in the folder tree in the lower pane.
Finally in order to open the web page they have to click in the lower pane on the official bookmark to open the web page.

Thats one unnecessary step.

Could you add an option that allows (when enabled) to open 
- the folder in the lower BMP2 pane 
AND
- the web page on the right
with ONE click on an item in the upper result list?

Thank you
Peter

**Comment by aaFn** [comment]
Hello @pstein, to do the second part of your demand in 1 click:
- In simple (default) mode, press Alt at the same time you click on the bookmark, and it will open in current tab (on the right)
- Alternately, set the "Advanced click" mode in the options page, and click on the text or favicon of the search result to open in current tab (on the right), or click on the blank part around the bookmark to only show it (in the lower BSP2 pane).

It doesn't do both show and open at the same time though = that was an old behavior which was removed, because annoying to many users. So for now you can only do one or the other at same time, see https://github.com/aaFn/Bookmark-search-plus-2/wiki/Mouse-clicks-and-modifiers-summary-table-(as-of-2.0.76)

If really needed to have both actions, which is not a frequent demand, I could modify the Alt key behavior in Advanced mode, so that it does both show + open, since there is already a way in that mode to do one or the other, independently.

Let me know.

**Comment by pstein** [comment]
@aaFin:

thank you for reply. However I cannot imagine why one click with two actions could annoy users.

Your offer with the Alt key is similarly unhandy: If users have to click two times or to click one time PLUS press Alt key
is  the almost the same effort.

So may I ask you to offer in the AddOn settings a new option which triggers with ONE click both actions?

This way all users are satisfied. ....and it shouldn't be too difficult to implement.
Thank you
Peter

**Comment by aaFn** [comment]
Well, it is still some effort each time I have to add an option. And then to modify the codes managing clicks (there are several types of them) and enter key (equivalent to click). And then test to ensure non regression.

May I ask that you describe a bit more the use case / benefit of having both the content open in current tab and showing at same time the bookmark in the bookmark pane ? Or basically, when do you need to show where is the bookmark in addition to opening it, and how frequent is that ?

Thank you in advance, aaFn.

**Comment by aaFn** [comment]
Closing for now, as no response, but you are welcome to reopen it when you want, or anybody else, to describe the use case / benefit to users and the frequency of such cases.

Thanks, aaFn.
