### ISSUE TITLE
Weird problem, when unloading tab

### ISSUE THREAD

**Issue by mzso** [aaFn/Bookmark-search-plus-2#183]
I had this happen a couple of time when undoing tabs with[ Undo Close Tab Button](https://addons.mozilla.org/firefox/addon/undo-close-tab-button/)
Somehow the bookmark editing dialog came up in a window, but with Tree Style Tab on it on the left. BSP2 wasn't even activated when these happened. Also, I clicked on a proper closed tab item, not some glitched item.
Is this some sort of conflict?

![kép](https://user-images.githubusercontent.com/4479090/115151070-9cf24500-a06b-11eb-9707-46e36eb085f8.png)

**Comment by aaFn** [comment]
Hi @mzso , I would suspect a combination of two things:

1. On FF side, when you open a new FF window, by default it activates the sidebar with active plugin in other last active window, if I remember well. So if that was TST, then you will see TST, if that was BSP2, it will be BSP2, if that was the native FF bookmark sidebar, it will be it .. etc ..
Given BSP2 property is in an FF window because of FF API limitations on popups, it inherits that behavior, and I do not see a way, or not easy at best, to change it.
2. On "Undo Close Tab Button" side, I infer that there is a "bug" (or is that a feature ?), that instead of reopening the last closed tab **in current FF window**, it opens the last tab closed across all FF windows .. and in your case, it happened to be the BSP2 Property window

Would be good to hear from @codefisher what is his view of it. If a feature, you may want to ask him to have an option to restore the last closed tab **in current window** ...

Not that meanwhile, you can by the way have an easy workaround, by right clicking at any tab label at top of your FF window, and by chosing the action to cancel last tab closed. That will do it.

Hope this workaround helps, while waiting for @codefisher views. Hope this callout will bring him here, else you would want to open an issue on his GitHub https://github.com/codefisher/toolbar_buttons or his forum https://codefisher.org/forum/ - although both seem down / not very active.

**Comment by aaFn** [comment]
Closing the issue on my side since we should wait for @codefisher 's fix, and there is a workaround meanwhile.
Thanks, aaFn.
