### ISSUE TITLE
Entire tree is expanded after clicking on search result.

### ISSUE THREAD

**Issue by JohnLukeBentley** [aaFn/Bookmark-search-plus-2#187]
Steps to reproduce:

1. Ensure your entire tree is collapsed. Open BSP2. Right Click on "Bookmarks Menu" > Advanced > Collapse all in branch.
2. Search for a bookmark. Click it in the search pane.

The result is highlighted and jumped to, as expected. However, the entire tree is now expanded (not just the local branch).

Current relevant settings:

![image](https://user-images.githubusercontent.com/18357541/118883856-15814580-b939-11eb-9d6f-a2fda1086a5d.png)

**Comment by aaFn** [comment]
Hello @JohnLukeBentley , not sure I get what is the problem ?
Given the option set for leaving the bookmark tree open after closing the search pane, all the path down to the shown bookmark should remain open, including all parent folders above it, not just the local branch. Is that what do you mean by "the entire tree is now expanded" ?

By the way, it looks like I have a regression, because when I do the sequence you mention, all gets closed on search close, so the option is not respected anymore - I'll check what is happening.

**Comment by JohnLukeBentley** [comment]
Hello @aaFn, I hope you are well!

The problem is that is not just the parent, and ancestors, above the found target is expanded. The problem is that every single folder in the entire tree is expanded.

If my target is "Pandoc - Home", then the parent "Pandoc" is expanded as expected. However, what I don't expect is the expansion of the folder "Support" (a sibling), and the folder "Latex" (a sibling of the parent).

![image](https://user-images.githubusercontent.com/18357541/118890302-ca1f6500-b941-11eb-92f0-d7ffb399a454.png)

This is new behaviour.

**Comment by aaFn** [comment]
Ah yes so that is related to the regression I was talking about, and which I just noticed thanks to your post 🙂 ...
You can see that all twisties except first unhidden level are all closed, while their content is shown. Leading to closing all folders except first, when the search gets closed.

When accelerating slightly the display in 2.0.91, I changed the HTML structure of folders, and mistakenly left one place in the code with the old structure.

I corrected. This is in 2.0.92 which is out now.
And checked again the code to only find that one, so hopefully no other regression.

Sorry, and thank you for the notification, aaFn.

**Comment by JohnLukeBentley** [comment]
Thanks! Fixed in 2.0.92.
