### ISSUE TITLE
Feature request: make BSP2 visible only when needed

### ISSUE THREAD

**Issue by eseb63** [aaFn/Bookmark-search-plus-2#188]
Hello,
on some sites, the space occupied by the BSP2 treeview is annoying , because some elements of the site are hidden, so we have to close BSP2 and reopen it later to create a bookmark from this site. It would be useful for the treeview to be minimized in the left margin, to give full space to the site. The user could then pin it if necessary to search or create a bookmark, or make it visible temporarily when moving the mouse on the left (like the taskbar). So the Treeview would be visible when needed and invisible the rest of the time if not.

what do you think about?

**Comment by aaFn** [comment]
Hello @eseb63 , do you mean the sidebar ? This is managed by FF itself, not by the add-on.

If some page content is hidden by the sidebar, then this is either a problem with the site not properly accounting for the viewport, or a problem with FF (but from experience, this is most probably the first ..).

I know some people have tricks to do things like you want using userChrome.css, but this is customization of your own that you need to do, and it can lead to other problems.

Search on the Internet, you will find some CSS to place in your  userChrome.css if you really want to do that.
Also look at #174 if you want inspiration, but as you will read there, there remain some incompatibility problems, and imperfections because this is a CSS hack to FF.

**Comment by eseb63** [comment]
yes, i meaned the sidebar...

clicking on the star icon to (un)hide BSP2 is what i usually do, but the treeview has to reload, that's i wanted to avoid.

i tried the css as shown in #174, but it's not satisfying if using drag and drop from address bar, and it doesn't work on my main firefox profile (maybe a conflict with another extension)

i found the sidebar+ extension (https://addons.mozilla.org/en-US/firefox/addon/sidebar_plus/) that handles auto-hiding (iframe option) and shows the firefox bookmarks ; drag and drop from address bar is available after the sidebar has been pinned.

it's that behavior that it would be handy to reproduce, but i don't realize if it's a lot of work to encapsulate BSP2 in such a sidebar ?

**Comment by aaFn** [comment]
Well, in fact the part in that add-on which can auto-hide is not a sidebar, this is content injected inside loaded pages, and interfering with them. Sorry, not really the spirit of BSP2, it is not meant to alter pages content, nor to inject anything in them.

Also, mind that this way of doing does not work on a number of pages, such as https://addons.mozilla.org/en-US/firefox/addon/sidebar_plus/ itself (try, you will see).

The real solution would be for Firefox to implement the behavior you want on the sidebar itself.
Indeed, this is not something that  an add-on can manipulate by itself, at least today.

**Comment by eseb63** [comment]
i searched on bugzilla... this feature has been requested since ... 19 years. the firefox team didn't implement it because some extensions did. These extensions are now obsolete, so the feature has been requested again 4 years ago, but it seems it's not a priority...

**Comment by aaFn** [comment]
Ok, sorry for that, things have been degrading when they started the new Quantum mode with FF57 😞 , And in fact that was the reason for me doing this add-on because we couldn't use alice0775's extension anymore, but this requires a lot more work than what alice0775 had to do at the time, and for something not so integrated as in the past ...

How long does the redraw take ? ( go to BSP2 options, activate traces at the bottom, and then a little text box appears below the search box .. select all its content, and if you can copy and paste here, would be great to see your times).

AaFn.

**Comment by eseb63** [comment]
I used the alice0775 extension and was very disappointed when it became obsolete. So, we have to thank you for writting and sharing this replacement tool, even more powerful than the original. I use it almost every time i search on the net.

BSP2 loading time is usually not an issue : it's very fast (less than 1 second) just after launching Firefox, but a few hours on the net after, Firefox performances decline and BSP2 is also longer to load ; so, the loading time is annoying only in these circumstances. 

However, having an autohiding sidebar would be a more handy and elegant solution, but i don't know if the Firefox Team will finally implement it or not...

**Comment by aaFn** [comment]
Closing as depending on FF to bring the functionality or to support it in a better way than today.
Thanks, aaFn.
