### ISSUE TITLE
Plugin hangs at "Wait background load ..."

### ISSUE THREAD

**Issue by printpagestopdf** [aaFn/Bookmark-search-plus-2#192]
The Addon immediately stopped working 3 days ago (perhaps FF update, but unsure actual FF Version 90.0.2). It endless shows in sidebar "Wait background load ...", but nothing happens.

Found a "Workaround", first clicked "Reload all bookmarks from FF now", and after this enabled "Never use FF Bookmark search API...".

But have to do this "Workaround" every time restarting FF (btw. checkmark is alway forgotten.)

**Comment by aaFn** [comment]
Hello @printpagestopdf , can you:
- Activate the trace option, close FF, then reopen FF and copy/paste here the content of the trace textarea which appears at top of the BSP2 sidebar, after the restart ?
- Also open the browser console (Ctrl+Shift+J), enable content messages in the little wheel at top right of the console, and copy/paste here the content you will see in there since start of BSP2 ?

It could be, from the described symptoms, that you are short on disk space where your FF profile is stored, because it does not seem to store and then retrieve properly BSP2 items on local store. Are you on Windows or another OS ? Can you verify your disk space ? And how many bookmarks do you have (see stats in the BSP2 options page)

Thanks, aaFn.

**Comment by printpagestopdf** [comment]
Oh, I am very sorry, but before reading your questions I uninstalled and reinstalled the addon and it worked perfect now. 

I did this before, but forgot to reset this settings keepUuidOnUninstall, and keepStorageOnUninstall to false. So probably the damaged local storage was not deleted and the error occured again.

Perhaps a small hint for you, I was looking with the WebExtension debugging to the local storage and the whole tree (on the left side) was empty -for sure a damaged local storage.

**Comment by aaFn** [comment]
Ok, good that you could get back to a working state.
Indeed, uninstalling the add-on and re-installing completely resets local storage for the add-on.
So that is a good way to cure such problems.
Nothing that add-ons can do about, unfortunately, as they totally depends on FF for that. So hopefully not happening often 😞
