### ISSUE TITLE
Remember exact state for easy swapping back and forth.

### ISSUE THREAD

**Issue by mzso** [aaFn/Bookmark-search-plus-2#198]
Hi!

Constant issue for me is that I use Tree Style Tab which I can't have open at the same time. So lacking a better way I have to switch back and for the between it and BSP2. Unfortunately BSP2 view is reset every time. It doesn't remember the state I left it. (For example a searched for a word, selected a result and opened the folder in the tree view.)

It would be nice if BSP2 remembered the exactly the state I left it in within a session. So I can change back-forth easily.

Lacking multiple sidebars it would be even better if appeared floating above the browser window, but I suspect that's not possible either.

**Comment by aaFn** [comment]
Hello @mzso , the only things BSP2 remembers between sessions are the folders open/closed state, and the cursor position.
Doing more than that could lead to instabilities, like if you closed BSP2 during a search because it was to long, or because it crashed (we are never protected from a bug ..), it would restart the search and lead to the same problem.

If you are really annoyed by the fact that FF is missing several sidebars (see this https://bugzilla.mozilla.org/show_bug.cgi?id=1328776#c41 on which both TST author and myself are asking - please vote 😀 !)
then you can apply a simple trick:
- open a new FF window as blank page (Ctrl-N)
- select its sidebar to be BSP2, and reduce the size of the FF window + increase size of BSP2 sidebar to show only BSP2 -> not perfect, there remains a little white space on the right, but that is not big
- or close sidebar, then right click on BSP star icon in the toolber + click on `Open BSP2 in a Tab` + close the blank page tab

This will provide the floating window you want ⚡ !

**Comment by aaFn** [comment]
Closing, with hope that the workaround is doing the function, while waiting that FF supports multiple sidebars.
Thank you, aaFn.
