### ISSUE TITLE
Enable "Sort by Name" at top level folders (Bookmarks Menu...)

### ISSUE THREAD

**Issue by peter-kehl** [aaFn/Bookmark-search-plus-2#214]
The built-in Firefox Bookmarks Manager & its sidebar shows "Sort by Name" context menu option for top-level folders like "Bookmarks Menu" and "Bookmakrs Toolbar". However, BSP2 shows this menu option only for folders within.

Could you check, whether the API does allow it at the top-level folders, too. If so, could you list this option, too, please?

Happy New Year.

**Comment by aaFn** [comment]
Correct, this is because those folders are protected, from BSP2 point of view, and such actions are disabled in BSP2 on such protected folders (e.g. recent tags, most visited bookmarks .. folders).

Is that is really important, I can look at how to add back specifically that menu item only on those 3 top level folders ...

**Comment by peter-kehl** [comment]
Thank you for explaining. Closing this ticket.
