### ISSUE TITLE
feature request: Copy a bookmark's URL

### ISSUE THREAD

**Issue by peter-kehl** [aaFn/Bookmark-search-plus-2#232]
Understanding that you don't want to overcrowd the context menu for bookmarks, but how about adding "Copy URL to clipboard", please?

Use case: I keep many tabs open, and often I know I have a bookmarked URL open already, and I don't want to open it in a (yet another) new tab (and I don't know where that tab is). I know I can get to it by entering percent % character in the Firefox URL bar, then a space, then some of the URL or its title. But to get the URL, currently I have to go through the bookmakr's context menu > "Properties..."

**Comment by aaFn** [comment]
Better suggestion .. how about this:
- I just discovered that now the Clipboard API for text is sometimes accessible without permission, when the page where add-on code is executed is active, cf. https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText (looks that this API call is active since FF 63)
- I tested and it appears that this applies to the sidebar when it has focus = considered as an active page
- So then, on doing Ctrl-C or right-click->Copy (and Ctrl-X / right-lick->Cut), it seems I can place any text in the clipboard, and therefore this could be the URL(s) of selected bookmark(s) as text
- And then you can do Ctrl-V or right-click->Paste where you want .. when implemented by the receiving application, including FF itself in the search tab `% ` bar if you want ..

**Comment by aaFn** [comment]
I made the above improvement in 2.0.105, published tonight.
Let me know if any problem.

Thank you, aaFn.
