### ISSUE TITLE
search menu flickering

### ISSUE THREAD

**Issue by getreadyforme** [aaFn/Bookmark-search-plus-2#24]
Here is what happens
https://www.youtube.com/watch?v=zM88XTzFUds

This happens both on Win 7 and Win 10 on different computers.  It happened in Firefox 58, and then on 59 after updating today.  

Sometimes it takes several seconds before it starts to flicker.  Sometimes is starts right away.  Once it starts, it keeps doing it until I close the menu.

I've included a screenshot of my extensions, but I've disabled them all and the issues still persists.  
![2018-03-13_172326](https://user-images.githubusercontent.com/7669787/37377758-186fda62-26e9-11e8-8eb1-76af70c4a00d.png)

**Comment by aaFn** [comment]
Hello @getreadyforme , thank you.
I believe I know what is the problem, and it's coming with 2.0.9, where I added a feature of updating the search panel if it is opened, when a favicon is refreshed.
I only happens for new users of the add-on, when they are i the initial phase of favicon fetching. After that, since favicons are cached, it shouldn't happen anymore.

I will fix that annoying behavior in 2.0.10 .. sorry for the inconvenience.

**Comment by getreadyforme** [comment]
well, it happens every time I activate the extension and start searching.  Thanks for looking into it.

**Comment by aaFn** [comment]
@getreadyforme , bug corrected in 2.0.10

Let me know if ok, or if you still have problems, but if the second, these should be of a different nature, so I am closing this issue.

**Comment by getreadyforme** [comment]
Nice!  All fixed.  Good work!
