### ISSUE TITLE
Smart Bookmark not correct in BSP2

### ISSUE THREAD

**Issue by kiwichick888** [aaFn/Bookmark-search-plus-2#266]
I have a smart bookmark in FF that shows the last 50 bookmarks added, but BSP2 shows only the last 10.

**Comment by aaFn** [comment]
Hello @kiwichick888 , what do you call exactly a smart bookmark ? Can you be more specific on the one you are using, or the search plasce: URL it is using ?

**Comment by kiwichick888** [comment]
Create a new bookmark with the following in the location field:
place:queryType=1&sort=12&maxResults=50

**Comment by kiwichick888** [comment]
> 2.0.113 is now published with the enhancement. Let me know if any problem, aaFn.

Thank you so much, I see all of the bookmarks now.

**Comment by kiwichick888** [comment]
Hi there, sorry, I can't say how long ago this started happening but something is wrong with the smart bookmark. I noticed today that there were many 'last added' bookmarks that weren't showing in the list, and it has wasn't showing favicons for nearly half of the bookmarks that are there [Img1]. They were all visible and had favicons in the Firefox Bookmarks [Img2]. So I deleted it and re-created it. Now the smart bookmark is showing all the correct bookmarks but none of them have favicons [Img3].
<img width="275" alt="screenshots" src="https://github.com/user-attachments/assets/f85ba97b-b20b-4fcc-8754-1e2ac05cc0e4">

**Comment by kiwichick888** [comment]
Today it's back to not showing all bookmarks. The last three bookmarks I've added aren't showing BSP2.

**Comment by aaFn** [comment]
Hello @kiwichick888 , try closing / opening the "recent bookmarks" folder.
If things do not get refreshed, the problem comes from the FF API in my view, because that part of the code was not changed since 2.0.113 above, and all it does is to call `browser.bookmarks.getRecent(maxResults)`, which returns the list and is then displayed (with favicon fetched if the bookmark is not already existing in the tree).

Also, could you make sure that this is the only one in the bookmark tree where you have "sort=12" ?
Are you sure there is not another one ? (export the bookmarks, and search them using a text editor)
Because, as said above, only one is supported in BSP2, and is properly refreshed / handled, the other(s) will stay static.

Last, look at the browser console (Ctrl+Shift+J, cf. https://github.com/aaFn/Bookmark-search-plus-2/wiki/Getting-and-providing-logs-for-debugging-BSP2) at the same time than closing / opening the "recent bookmarks" folder, and let me know if you see any error message from BSP2 in there.

**Comment by kiwichick888** [comment]
> Hello @kiwichick888 , try closing / opening the "recent bookmarks" folder. 

I've tried that several times.

> Also, could you make sure that this is the only one in the bookmark tree where you have "sort=12" ?

This is the only one with sort=12.

> only one is supported in BSP2

This is the only smart bookmark I have.

> Last, look at the browser console and let me know if you see any error message from BSP2 in there.

No errors. No information at all.

**Comment by aaFn** [comment]
Ok, so the problem must come from Firefox itself, because closing / opening triggers a re-rad from the API, and if you have no error in the console, that means it is completing ok

**Comment by kiwichick888** [comment]
> so the problem must come from Firefox itself

Yes, I think you're right. I'm using the current FF v133.0. I have a backup of v126.0.1 which I checked and the issue isn't present there. So I tried a clean install of v133.0 and installed only BSP2, and the issue is present. Hopefully, something will change in the future with FF to fix the issue and in the meantime, I'll just have to use FF bookmarks to access my smart bookmark.

**Comment by Gitoffthelawn** [comment]
It will be good to report the issue to Mozilla on Bugzilla: https://bugzilla.mozilla.org/

**Comment by kiwichick888** [comment]
> It will be good to report the issue to Mozilla on Bugzilla: https://bugzilla.mozilla.org/

Would they be interested in a bug affecting an addon?

**Comment by kiwichick888** [comment]
> It will be good to report the issue to Mozilla on Bugzilla: https://bugzilla.mozilla.org/

That's a good idea. Hopefully aaFn will think so, too, and do it. I don't think there's much point in me doing it because any discussion/questions about it will undoubtedly involve technical stuff about the app that I won't be able to answer.

**Comment by aaFn** [comment]
Hi there, unfortunately, I am not able to reproduce the problem on my side .. so I am not in position to open a bug and to describe it 😞

An idea maybe, in case this could be a workaround: when the problem occurs again on your side, try the `Reload all bookmarks from FF now` button in BSP2 options.
Let me know if that does anything.

**Comment by kiwichick888** [comment]
> try the `Reload all bookmarks from FF now` button in BSP2 options. Let me know if that does anything.

I tried that but it didn't fix the problem. In fact, now only the title of the smart bookmark is present, there are no bookmarks in it. I've even uninstalled and reinstalled BSP2 but nothing has changed.

<img width="170" alt="2024-12-19_105357" src="https://github.com/user-attachments/assets/7cdd05c1-5f15-44fd-a8ab-1489e97669c2" />

**Comment by aaFn** [comment]
Ok, I am travelling tomorrow, I won't be able to look at that before Friday. It could be that there is another bookmark with "sort=12" somewhere .. I may need to add some traces to verify, let's see on Friday or during the week-end if you agree.

**Comment by kiwichick888** [comment]
> Ok, I am travelling tomorrow, I won't be able to look at that before Friday. It could be that there is another bookmark with "sort=12" somewhere .. I may need to add some traces to verify, let's see on Friday or during the week-end if you agree.

I'm happy to do whatever works for you so we can hopefully get a resolution. I did initially say that I don't have another bookmark with "sort=12" but that was based on your advice to 'export' the bookmarks. 

What I have noticed is that the export option saves the bookmarks as an html file and there is no "sort=12" for any bookmark other than the smart one. 

However, if I use backup instead of export, the bookmarks are saved as a json file and "sort=12" appears twice in there. One is for the smart bookmark. The other one appears right at the end of the json file but I don't know what it's for because it doesn't have a 'titled' bookmark associated with it. I'm not even sure it's anything to do with a bookmark, or just some 'closing' code for the file because if I delete that part of the code then restore and backup the bookmarks again, the code is back at the end of the json file.

Here are both bookmark files for you to look at, if you think it might help.
[Firefox bookmarks.zip](https://github.com/user-attachments/files/18190710/Firefox.bookmarks.zip)

**Comment by aaFn** [comment]
Hello @kiwichick888 , ok, I see nothing abnormal in the 2 files. I can't even find 2 times the "sort=12" string in the .json file. It might be the editor that you are using which has a bug for very long 1 line JSON statements ?? I am examining it with Visual Studio Code on my side.

Even stranger, when I restore your .json file on an independant/new instance of Firefox 133 with its own BSP2, there is no problem, the "_Last 50 Bookmarks Added" smart bookmark is properly handled by BSP2 and displayed with the folder twistie, and it displays content inside it which corresponds to your last 50 bookmark entries, per their creation date.
The native FF bookmark sidebar also behaves well, and displays the same content under the smart bookmark.

So I am really not sure of what is happening.

**Comment by Gitoffthelawn** [comment]
Quick thought: Could it be a pref difference between the Firefox profiles for @kiwichick888 and @aaFn?

**Comment by aaFn** [comment]
Hello, good news, while playing with diverse cases of multiple instances, for improving the code to better handle those cases, I could reproduce the problem above of the "smart bookmark" special folder not being updated anymore and having empty favicons
= I can confirm to you that this is a case of having 2 or more instances of the same smart bookmark "sort=xx" place: query.

So for some reason, at one moment, you must have gotten 2 instances of the "sort=12" smart bookmark, and this trigerred the problem. Then, as the code was not handling very well that case, this created the symptom above.
Later on, with the "reload from FF API", the special folder became inactive and empty, because BSP2 saw the other instance farther in the tree, during the reload.

What is strange is that your export and your backup only show 1 instance .. I can only infer that at some point the bookmark DB became a bit corrupt and contained 2 instances (or more ..), and that now again you only have one after your diverse manipulations.
I can tell though that with my multiple tries and experiments, the native FF bookmark sidebar doesn't behave so well with those smart bookmarks and multiple instances either .. from time to time, it looses the special icon and has a standard folder icon, other times when moving it, it is in fact duplicating it ... and so I found myself with 3 or 4 instances .. that doesn't seem all very clean 😦 

I modified the code to be more robust, I will publish it tomorrow.
I cannot guarantee that the problem of multiple instances won't come back, but now it should be better handled.
There remains the problem of "where is/are the other instance(s) ?". Since the search is not looking at URLs in folders/special folders, neither in the native FF bookmark sidebar nor in BSP2, there is not an easy way to find that.
I will think a bit about it ...

**Comment by Gitoffthelawn** [comment]
@aaFn That's an impressive investigation!  Any Bugzilla issue reports to follow that resulted for the native FF bookmark sidebar?

**Comment by aaFn** [comment]
Yep, problem created on bugzilla = https://bugzilla.mozilla.org/show_bug.cgi?id=1938806

Ok, I resolved the question of "Where is/are the other instance(s) ?" by now displaying smart bookmarks in the BSP2 search result.

I was skipping them in the past because they were missing their title in some cases, and because some more were returned which were not really in the full list of bookmarks, creating an undefined pointer exception in my code because non-existing -> namely the History, Download and Tags "smart bookmarks". Not happening anymore, but this is still true in old FF versions which I support (BSP2 supports all FF versions from 58).

I added code to properly handle those cases.

Plus I am now displaying their URL, e.g. "place:queryType=1&sort=12&maxResults=50".
So it is now easy to pinpoint them, click on them and find them in the bookmark tree .. etc ..

This is in 2.0.132, which is out now.
Let me know how that goes .. thanks, aaFn.

**Comment by kiwichick888** [comment]
> I can't even find 2 times the "sort=12" string in the .json file.

That would be because I'm an idiot and gave you the wrong one 🤦‍♀️That was the one I had edited to take the second sort out to see if it made a difference when I imported back into FF.

If it helps at all, seeing as you think you've got a solution, here's the correct json file:
[bookmarks-2024-12-26.json](https://github.com/user-attachments/files/18249250/bookmarks-2024-12-26.json)

**Comment by kiwichick888** [comment]
> This is in 2.0.132, which is out now.
> Let me know how that goes .. thanks, aaFn.

I uninstalled the previous version just to exclude anything that might have interfered with the new version, installed the new version and now I have nothing at all in the smart bookmark. All I have is the smart bookmark title.

<img width="149" alt="2024-12-26_165651" src="https://github.com/user-attachments/assets/14ccf702-2faf-4c4e-b711-f47276a363bd" />

**Comment by aaFn** [comment]
Ok, this is indeed because you have a second one ... do a BSP2 search on "sort=12" and you will find it in BSP2.
It is in Mobile, and it has no title !!

`{"guid":"DVZv0h2hz-ZW","title":"","index":218,"dateAdded":1728772925496000,"lastModified":1728773358000000,"id":1519,"typeCode":1,"type":"text/x-moz-place","uri":"place:sort=12&excludeQueries=1&maxResults=50&queryType=1"}
`

On restore in my BSP2 test instance, it didn't appear, because I have no Mobile folder on my side .. so all was ok.
Then I did a reload from FF API, and it appeared.

You have to go to the native FF bookmark sidebar, and find it in Mobile, and remove it ... Or give it a title, and remove the first one. What is sure is that BSP2 will not work with 2.

And yes, this is the problem of FF that when it syncs with your mobile device bookmarks, they are not merged, they are placed in a separate folder and they are duplicated 😢

**Comment by kiwichick888** [comment]
> It is in Mobile, and it has no title !!
> You have to go to the native FF bookmark sidebar, and find it in Mobile, and remove it

Thank you, thank you, thank you!!!!! I did the BSP2 search and found the two results for sort=12, as you said. When I went to the FF sidebar and checked the Mobile Bookmarks, there was an folder in it called 'no title'. It was full of bookmarks that all had titles but were already present in the Bookmarks Menu. So I deleted the 'no title' folder and that fixed it immediately. Thank you so much for all the time and effort you've put into investigating this for me. It so appreciated.

**Comment by aaFn** [comment]
Ok, glad that all is good now, let me know if any problem later.
Thank you, aaFn.

**Comment by kiwichick888** [comment]
> let me know if any problem later

I've already had the 'no title' reappear so it may be an ongoing thing to do with Firefox Android Mobile Bookmarks. But I know what to do to fix it now, so I can deal with it. Thanks again for all your help.

**Comment by Gitoffthelawn** [comment]
@kiwichick888 For posterity, can you add a quick post explaining how to fix it so future readers will see the solution at the end of this issue report?

**Comment by kiwichick888** [comment]
> @kiwichick888 For posterity, can you add a quick post explaining how to fix it so future readers will see the solution at the end of this issue report?

I already explained how I did it three replies before your one.

"I did the BSP2 search and found the two results for sort=12, as you said. When I went to the FF sidebar and checked the Mobile Bookmarks, there was an folder in it called 'no title'. It was full of bookmarks that all had titles but were already present in the Bookmarks Menu. So I deleted the 'no title' folder and that fixed it immediately."
