### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by VLM-TechEd** [aaFn/Bookmark-search-plus-2#270]
Thank you for responding to my last question. Unfortunately, you closed the issue so quickly that you apparently never saw my follow-up questions. So here they are. If there is a better way to ask questions, please let me know. Also, FYI, I have limited eyesight. My eyes sometimes miss things these days. So, I apologize if I missed an answer to a question.

1. Is there a shortcut to open BSP2 in a tab? Or is a bookmark the only way?

2. Is there a way to export and import BSP2 preferences?

3. Can this extension support a dark theme in tab view? I have the Theme set to Dark in about:addons. I have the settings item set to dark. And I am using the Dark Background Light Text extension. This is a great combination for me, generally speaking.

Thank you kindly!

**Comment by aaFn** [comment]
Hello @VLM-TechEd , the base rule before asking question is to read docs, or to search if they where not already answered previously. All your questions have an answer already.

I answered 1) in your previous question #269, which tells you 2 ways to open BSP2 in a tab.
None of them is through a bookmark. And none of them have a shortcut.

Your question 2) is already being handled here #267, which is currenlly open, there is no need to open another thread for it.

For question 3), look at the BSP2 options page, where you have an option to match the active FF theme colors. Then if you have a dark theme active, BSP2 will use the same dark background color.

**Comment by VLM-TechEd** [comment]
Thank you.

 

Regarding question #1, clear, and the bookmark also works well. Some of us older folks have tired, sore wrists and forearms, and we seek out solutions that avoid use of a mouse. In other words, I consider this an accessibility issue that should be addressed timely. In my experience (more than 45 years using computers), shortcuts are pretty standard fare, and from what I understand they are fairly easy to implement. So, this is a request for a user-definable shortcut (presumably via extension shortcuts in about:addons) with any default you wish. If both the sidebar and a tab are open, as you suggest, it would also be nice to have a shortcut to toggle focus between them. Then it would be keyboarding all the way. 

 

Regarding question #2 about exporting and importing settings, you asked for input about a format. I’m no programmer, but I notice that many extensions, including some with far more user settings than BSP2 has, seem to use .txt config files. They are simple and, I think, universally cross-platform. Every setting is given a name and a set of possible values that can easily be written and read. I assume that you have already named every setting and defined a corresponding set of allowed values in your existing code, so perhaps you could use the same names.

 

Regarding question #3, I had already checked the option Match FF Theme Colors. But no matter which method I use to open BSP2 in a tab, it comes up with black text on a white background. I don’t know why. If there are logs or other data I can extract that might help you figure that out, I am most willing to follow any lead you suggest.

 

Once again, thank you!

**Comment by aaFn** [comment]
Hello @VLM-TechEd ,

on shortcuts, have a look for example at #265, shortcut is a problem in FF = there are not many left free by FF itself, you cannot redefine the ones of FF to your taste to make room for the ones you'd like, freeing the ones you never use, and worse, the free shortcuts are not the same across the 3 platforms of Windows, Linux and MacOS ..
In short, it is not easy to find shortcuts for extensions, and implementing them is not easy either because of conflicts with FF, and some random behavior that I observed in handling them ..

Note: if you have wist problems, you can like me use "mouses" with trackballs, they are much more comfortable, as precise, and as fast .. I do not want to make any advertisement, so just take this link as an illustration https://www.logitech.com/en-us/products/mice/mx-ergo-wireless-trackball-mouse.html


On your last point, if the behavior of BSP2 background is different in sidebar and in tab, then that means you have another extension interfering, which is overring things above BSP2 -> I would start investigating this path first.
If the behavior is the same and the background color is ignored both in sidebar and in tab, then thre is either a bug or a problem in the theme.
On my side, when I test with the standard FF dark theme, it all works fine (Windows 10, FF 112.0).
On your side, what happen with the standard FF dark theme (and which OS and FF versions do you have ?)

**Comment by VLM-TechEd** [comment]
I have created more than two dozen shortcuts of my own shortcuts using extensions that enable such capabilities. There are plenty of shortcuts available. On Windows, alt-B appears to be available. I am currently using ctrl-alt-B as the shortcut to open the BSP2 sidebar, but I cannot remember whether you provided it or I created it. Anyway, alt-B would seem a natural companion for a default shortcut. It does not appear to conflict with any built-in shortcut, and in the event of a shortcut conflict with another extension, the user can sort it out in about:addons. 

 

Regarding wrists, you obviously don’t have any problems with yours. Trackballs are NOT the answer for a great many people. Proper software accessibility is the answer, and this is a developer responsibility. Properly positioned keyboards work best, and tens of millions of us know this. 

 

Regarding the theme issue, I presently have the BSP2 sidebar and tab open side by side, and both appear as black text on a white background. When I disable the Dark Theme Light Background extension and reload the BSP2 page, both the sidebar and the tab remain black text on a white background. I restarted Firefox and found the same result. In other tabs, the BSP2 sidebar appears as black text on a white background and the tab adjacent appears correctly, as white text on a black background. As reported earlier, I have the dark theme enabled in about:addons > Themes, and I have selected “Dark” in the settings. What else can I explore?

 

Thank you for your suggestions and for your continued correspondence.

**Comment by aaFn** [comment]
As I told you, shortcuts are not so easy to manage for FF extensions, especially when you have to manage several platforms. E.g. Alt-B that you mention is free in Window, but it is not free in Linux.
Basically, you have to register the shortcut in the extension manifest file, it cannot be created as needed, and then you need to design a specific set of UI buttons to make it changeable in the extension options page for each shortcut key that you want to.manage. This is significant code investment each time. So to do only for very frequent actions for all users .. and opening BSP2 in a tab is not a frequent action for the majority of users.

On the theme issue, selecting “Dark” in the settings is not seen by extensions, or I didn't find a way for that.
The only thing which seems to work with the web extension API is themes, as it appears.
If you activated the Dark theme in about:addons, then this is ok, BSP2 sees it and follows it = this is working on my Windows, Linux and MacOS.
From your post, I see you are on Windows, but can you tell me which version of Windows ?

**Comment by VLM-TechEd** [comment]
Shortcuts – understood, though it is quite common, I think, to use different shortcuts on different platforms. Accessibility does not concern you greatly, that is clear, and that is a choice, not a moral imperative. 

 

Dark – I twiddled with various settings and have it all working now. The problem dark theme users face is that not all web designers honor them (or know how). So from time to time, one must deactivate the dark theme, do whatever is needed on a given page, then reactivate the theme. This happens, in particular, in web pages that contain user-selectable UI elements such as buttons, sliders, and checkboxes. So I just have to stay more on top of all such changes I make here and there.

 

Thank you for your kind and patient support. Have a blessed day,

Elchanan

**Comment by mapibid** [comment]
Hello, ok, glad that you sorted out the dark theme.

On shortcuts (and accessibility), everybody has their own notion of what should be accessible or not, and have their own profile of usage. Ideally, shortcuts should be easily configurable, and then I could register a list of available accelerators to FF that users could pick and configure/assign as they want on accelerator keys.

However, this is not how FF is managing accelerator, it is making things very difficult for add-ons .. all of them have each to add and code their own logic to manage accelerators, and the more flexibility we want, the more code we add just for something which is not the core function.
Worse, you can notice that FF does not provide a page to configure its own accelerators .. so the problem is with FF in the first place.

Therefore, it is not a question of caring or not, it is a question that the effort is significant, is outside of the main objective of the add-on (which is done on spare time, let me remind that fact), and anyway cannot fit with what people want because they all want something different, and coding something flexible enough is a project on its own ..

Net is that FF wide accelerators are too much a pain for an add-on developer to do something which can satisfy everybody ... Thank you for your understanding, and sorry for that.

**Comment by VLM-TechEd** [comment]
Thank you for all this explanation. For decades, Mozilla has made things difficult for extension developers, in spite of the fact that in their early days, extensions were what made them successful. Same problem at Apple vs. Microsoft during the 1980s–90s. Microsoft licensed Windows; Apple refused to license MacOS. Microsoft crushed Apple (in those days). If Steve Jobs hadn’t been such a dufus about this, Apple could have owned the desktop computer industry. (They actually did, for a while.)

 

I do disagree on one point, however academic it may be. While I agree that people have different notions of accessibility, wide availability of keyboard shortcuts has been a universally recognized solution, or at least partial solution, since the first desktop GUI was developed at Xerox PARC back in the 1970s. Steve & Steve (Jobs & Woz) got the ideas that became Lisa, then Macintosh, during a tour at Xerox PARC. But perhaps I show my age. 😊

 

I hope you never experience the kind of problems that some of us cope with every moment of every day. I wouldn’t wish this on anyone, ever.

 

Have a blessed day.

.

**Comment by mapibid** [comment]
Thank you @VLM-TechEd , I do agree on all the points you mention, including the value of accelerators, and as soon as FF facilitates things and lowers the effort bar, I will make a whole list happen (you are not the only one asking for accelerator keys).

Have a nice day.

**Comment by VLM-TechEd** [comment]
And you. I won’t hold my breath on the FF side of things, though.
