### ISSUE TITLE
Font size no longer honored

### ISSUE THREAD

**Issue by ragkag** [aaFn/Bookmark-search-plus-2#275]
Under Options>Override font size, the font size doesn't appear to work anymore.  I believe it started with Firefox 113 (which I just installed).  If I change it, then go back to the Options, my change doesn't show.

I just realized that the extension was updated to 2.0.115 and this is when the font issue started.  I was previously on 2.0.113

**Comment by aaFn** [comment]
typo in the code introduced in 2.0.114 on the setFontSize option .. I hate javascript and all these untyped/unstrict languages (php, python, perl .. and other script kiddy things) which make people believe they are faster while in fact they are slower, because like anybody else they make typos, copy/paste and other stupid errors, and these go to prod undetected ... where a normal typed language immediately yells and draws your attention to correct the thing - <Rant off>

Corrected in 2.0.116, which is out already => please refresh to the latest version 😄 .

**Comment by ragkag** [comment]
Thank you for this quick fix.  Really love this extension.  How do I donate?  I'm new to GitHub.
