### ISSUE TITLE
 Opening Multiple Selected Bookmarks - Enhancement Suggestion

### ISSUE THREAD

**Issue by Cr8zyIvan** [aaFn/Bookmark-search-plus-2#277]
Complementary to my previous Enhancement Suggestion Request (_Shift + Click on "Open All in Tabs"_ which was very well executed by the way), I believe it would also be useful to be able to Open Multiple _Selected_ Bookmarks.

When only 1 Bookmark is Selected, all items in the Context Menu are available. When 2 or more are Selected, most items are greyed out. If the 4 first items were to be available (<Open>, Open in New Tab, Open in New Window, Open in Private Window), it would then be possible to open only the Tabs you want (Tabs that you select). The other option I see is to open "the Parent Folder" of the Bookmarks you want. As an example in this case, if there are 10 Bookmarks in the Parent Folder and you only want to open 5 of them, 5 other Bookmarks must also open, that you must then close.

**Comment by aaFn** [comment]
Hello @Cr8zyIvan , this should be in 2.0.117.

Open in New Tab, Open in New Window, Open in Private Window will be active in the context menu on multiple selections, but only if there is no folder within the selection.

**Comment by aaFn** [comment]
The new feature is now in BSP2 2.0.117, which was just published.
Let me know if any problem, thank you, aaFn.

**Comment by Cr8zyIvan** [comment]
Oh wow, that's awesome, I'll check it out!

**Comment by Cr8zyIvan** [comment]
It seems to work very well. I tested it out just a little bit so far. I noticed two slight glitches.
- Opening a Bookmark Folder (Selected Folder) in a New _Window_ ➔ Opens all Bookmarks inside in Reverse Order.
- Opening Multiple Bookmarks (Selected Bookmarks) in New _Tabs_ ➔ Opens all Bookmarks inside in Reverse Order.

Other than this, I haven't noticed anything. Great job!

**Comment by aaFn** [comment]
Hello @Cr8zyIvan, thisall depends on the order in which you made the selection = the one you place first in the selection will show first in the open list.

In other words, the open actions follow the order in which the bookmarks were added to the selection (more or less, because there is a random factor added by FF due to the parallel and "javascript "Promise" nature of the API).

Mind that display order is not really relevant to the bookmark structure = things can be displayed one way, and have a different internal "order" ... so the logic I took a long time ago in the multiple item selection is to keep the order in which things are added.
