### ISSUE TITLE
Key typing inactivity timeout has a problem when IME on

### ISSUE THREAD

**Issue by ih000667** [aaFn/Bookmark-search-plus-2#278]
I'm Japanese and I often use an IME when I type text. I hope that the inactivity timeout during key input will not work during Japanese conversion using IME. This is because the key input during character conversion is a little slow. If the search starts at that point, the desired conversion will not be possible.
I know the option  'Wait for "Enter" in search box to launch search(no trigger on key typing inactivity timeout)'  exists, but I don't want to use this.  A few older versions didn't have this problem.

Thanks in advance.

**Comment by aaFn** [comment]
Hello @ih000667 , it is not possible for the add-on to know if IME is on or not. The IME is an OS level function, not something that can be seen.
So not sure what you need. Is it to have an option to be able to set a bigger inactivity timeout ?

**Comment by ih000667** [comment]
Thank you for your reply.

> Do you mean there is an option to set a larger inactivity timeout?

I think that's one of the solutions.
Has the inactivity timeout changed in recent updates? Because there was no particular problem with the version I was using before, so I would like to use it like the previous situation.

**Comment by aaFn** [comment]
Hello, no, nothing has changed on that area since long.
It must be something else which changed, either in Firefox or in your OS.

**Comment by ih000667** [comment]
Version 2.0.109 works fine with the latest Firefox, but after 2.0.110 there is a problem. So maybe this is a plugin issue?

**Comment by aaFn** [comment]
Thanks for the investigation, so this dates to a modification in August last year, probably related to #247 as you can read in there that there is an impact on IME, and advising to use the option `Wait for "Enter" in search box to launch search (no trigger on key typing inactivity timeout)`

Since then, I reworked the code for managing options, and it is now much easier for me to add options (I had never foreseen initially that things would grow so much on options), so I guess now is a good time to introduce an option to disable the suggestions dropdown.

Or let me know if you see things differently.

**Comment by ih000667** [comment]
As long as this doesn't cause too much confusion for users, I agree with your suggestion and would greatly appreciate it.

**Comment by aaFn** [comment]
The new option to disable suggestions dropdown is now active in BSP2 2.0.117, which was just published.
That should solve the bad effect you mention.
Let me know if any problem, thank you, aaFn.

**Comment by ih000667** [comment]
The new option is very good for me.
Thanks for adding this option.
