### ISSUE TITLE
No longer able to delete bookmarks

### ISSUE THREAD

**Issue by ragkag** [aaFn/Bookmark-search-plus-2#282]
For some reason, I am unable to delete bookmarks.  Right-click>delete does nothing.  Firefox 118.0.1, Bookmark-search_plus-2 2.0.118

**Comment by aaFn** [comment]
Hello @ragkag , still works perfect for me.
Is that on any bookmark ?

I would suggest you do a "Reload from FF API" first in the options page, before retrying

**Comment by ragkag** [comment]
I did a “reload” then tried deleting 6 different bookmarks from different folders and none of them deleted.  Nothing happened after I clicked delete.

As far as I know this was working.  I don’t delete bookmarks often.

**Comment by ragkag** [comment]
I also created a new folder and was not able to delete it either.

**Comment by aaFn** [comment]
Ok strange, can you apply this procedure https://github.com/aaFn/Bookmark-search-plus-2/wiki#debugging-bsp2
to take some traces of what is happening when you try to delete 1 bookmark

and then post here the result of the trace ?

Thank you aaFn.

**Comment by ragkag** [comment]
I think I did what you asked.  Strange that the only message I see is below.  I actually did this twice with two different bookmarks with the same result.  I only posted the

2nd one.

 

Uncaught (in promise) Error: No bookmarks found for the provided parentGuid undefined

**Comment by ragkag** [comment]
After I submitted what you asked for, I decided to try this:

                I went to View>Sidebar> and switched from “Bookmark search Plus2” to “Bookmarks” and I was then able to delete bookmarks and folders.

                I then switched back to “Bookmark search Plus2” and could NOT delete bookmarks.

**Comment by aaFn** [comment]
I am out in a location with very little bandwidth, will try to think about this, but the message with ParentGuid is indeed strange.
I may create a special debug version for you to investigate, but then that means on week of OOctober 23rd when I am back. Hope this is ok.

**Comment by ragkag** [comment]
No problem.  I appreciate you trying to fix it.  Creating a special debug version will take a lot of your time.  Unless you have had this

Issues with others I’m good with the way it is.  I can still delete bookmarks using the technique I described in my other email.

Your Bookmarks search plus 2 has been a godsend for me.  I have essential tremor in my mouse hand and I was continually moving

bookmarks to other folders without even knowing it.  You’ve made it possible to find those moved bookmarks.

 

Thank you. And if you decide to create the debug version I’ll be glad to test it for you.  Stay safe.

 

Bob Gregory

**Comment by aaFn** [comment]
One more thing, could you confirm if in the BSP2 options page you enabled or disabled the BSP2 trash ?

The option is called "Create & use BSP2 trash folder ..." in the section "Bookmark history & undo/redo"

**Comment by ragkag** [comment]
Yes, I do have this option turned on.  Just an FYI, I have a laptop with the same OS and Firefox versions and deleting bookmarks works fine.

I tried clearing/disabling/enabling the trash folder but still can’t delete anything. ???

**Comment by ragkag** [comment]
A little more info.  I tried to clear the trash folder (about 30+ bookmarks) but it never cleared.  If I disable the trash folder, deletions work fine.

**Comment by aaFn** [comment]
Interesting .. so the problem is "Move to trash", and only on your specific instance. That points to a data problem tied to the "hidden" BSP2 trash folder, a priori. Maybe not well recognized because of its name, or several of them created in past, or not at its place ..

When you look at the native FF bookmarks sidebar, how many "_BSP2 trash folder for undo of.._" do you see ?
Is it / are they under "Other Bookmarks" ? Or somewhere else ?

Note: you can also make it visible in BSP2, by ticking the corresponding option in the "Traces / debug" sectoin of the BSP2 option page.

**Comment by ragkag** [comment]
When you look at the native FF bookmarks sidebar, how many "BSP2 trash folder for undo of.." do you see ?
Is it / are they under "Other Bookmarks" ? Or somewhere else ?

If I understand you correctly, using the native FF Bookmarks sidebar I do NOT see the "BSP2 trash folder for undo of..".

If using BSP2, I see it under “Other Bookmarks”.  There are about 30+ bookmarks within the folder.  A few are duplicated.

**Comment by aaFn** [comment]
> If I understand you correctly, using the native FF Bookmarks sidebar I do NOT see the "BSP2 trash folder for undo of..".

Wow, that is not normal !
That would mean a parent - child relationship is broken in the FF bookmarks database ..

You should see it right under “Other Bookmarks”, like in BSP2 when you make it visible by ticking the corresponding option in the "Traces / debug" section.

If that is not the case, then a corruption made its way in the FF DB, and the best way to cure it should be, in this order:

1. While the BSP2 trash folder is visible in BSP2 (by ticking the corresponding option in the "Traces / debug" section)
2. Untick the option "Create & use BSP2 trash folder ..." in "Bookmark history & undo/redo" section
3. This will delete the BSP2 trash folder and all its content (you should be able to move what you want below it to somewhere else before doing so, so that you can keep them if you want)
4. It won't appear anymore in BSP2
5. It shouldn't appear either in the FF native bookmark sidebar
6. Tick again the option "Create & use BSP2 trash folder ..." in "Bookmark history & undo/redo" section
7. This will recreate it, empty
8. It should now appear also in the FF native bookmark sidebar
9. Try a few "delete" = the bookmarks you delete should move into the BSP2 trash .. and you can do undo/redo as needed.
10. When all ok (I hope), you can hide the BSP2 trash folder in BSP2 (by unticking the corresponding option in the "Traces / debug" section)
11. It will still be visible in the FF native bookmark sidebar

Let me know how things go .. 🤞

**Comment by ragkag** [comment]
After step 4 below, the BSP2 trash folder still shows, with bookmarks in it.  I didn’t go any further.  Should I try to manually delete it?

**Comment by aaFn** [comment]
Ok, yes, if the delete action is enabled on it in BSP2 (which would mean it is no more recognized as the BSP2 trash folder, and so it should be processed like a normal folder), then try to delete it,

If the deletion is working, then you can continue with steps 5 and so on ..

Let me know the results.

**Comment by ragkag** [comment]
Well, this is what happened:

1.	With the BSP2 trash folder option disabled, I attempted to delete the BSP2 trash folder by right-clicking it but there was no “Delete” option in the context menu.
2.	I then went back to the native FF bookmarks and in the “Other Bookmarks” folder the BSP2 trash folder and all my previous “Other” items were gone EXCEPT for

                      two identically named bookmarks that I had previously saved. 

3.	I was able to delete the two identically named bookmarks.
4.	I then enabled BSP2, went to options, and enabled the trash folder.
5.	I could now see the BSP2 trash folder and I can now delete bookmarks again, and they do go to the trash folder.
6.	Case closed.

 

Thanks for the help.  Have no idea what happened.  Not sure how I got two identically named bookmarks in my “Other” bookmarks section. Can you have two of the same

named bookmarks if they are pointing to different URLs?

 

Enjoy the rest of your weekend

**Comment by aaFn** [comment]
Ok, great that you are functional again.

That doesn't explain why the corruption occurred. It is normally not possible to lose the parent of a bookmark, and there is no way to force it through the API. However, I did get reports in the past of such things - not because of BSP2, since some of those reports pre-date the first version of BSP2, and BSP2 was able to find them and then allowed to reattach them by moving them to a new parent -, but obviously this happens.
Unfortunate that in this case it happened on the BSP2 trash folder itself .. which makes things more complex to handle since I protect the BSP2 trash folder from BSP2 user manipulations to avoid bad accidents (maybe I should add an option to unprotect it, for handling such extreme cases ..).

Anyway, hopefully this won't come back, but that ever does, let me know.
Thank you, aaFn.

**Comment by Gitoffthelawn** [comment]
If any of the Firefox behaviour can be accurately described (or even better, replicated), I think it would make a very worthy issue report on: https://bugzilla.mozilla.org

**Comment by aaFn** [comment]
Hello @elandorr, so like @ragkag above, do you still see the BSP2 trash folder under "Other bookmarks" in BSP2 when you do the following:
- Tick the "BSP2 trash visible" option in the "Traces / debug" section of BSP2
- Untick the option "Create & use BSP2 trash folder ..." in "Bookmark history & undo/redo" section
??

**Comment by aaFn** [comment]
A bit weird indeed, and not the least about FF manager modifications not appearing live in BSP2 !!

By "refreshed from ff" in your first post above, did you mean pressing the button to "Reload all bookmarks from FF" in the BSP2 options ?
If not, what did you mean ? And what happens when you press that button, do the problems still remain ?

**Comment by aaFn** [comment]
Ok, let's say no hurry to get to the next version for now.
One more thing to make sure I understand:
- When you add, modify, move .. a bookmark in BSP2, that works fine, whether the BSP2 trash folder is enabled or not, correct ?
- When you delete a bookmark in BSP2, and the BSP2 trash folder is disabled, this works also, correct ?
- It is when you delete in BSP2 while the BSP2 trash folder is enabled that things do not happen, still correct ?

Or so you have different symptoms ?

**Comment by aaFn** [comment]
Ok, I just tested under ESR 115.5.0, all works fine on this side .. so there is nothing I can investigate.
I published a new version of BSP2, 2.0.121, to do some cleaning of unhomed BSP2 trash folders, or duplicates, in case something went wrong in the past, when disabling the BSP2 trash.

So can you update your BSP2 instance to 2.0.121, then disable the BSP2 trash option, and then exit from Firefox (this last step is important) ?
And then restart Firefox, and go to the BSP2 options and re-enable the BSP2 trash option.
That should at least address the case that @ragkag met, and hopefully  yours also.

Let me know.

**Comment by aaFn** [comment]
Fyi, I uploaded a new version 2.0.122 with improved handling of diverse error cases on the BSP2 trash :
- Immediate cleanup of all undue instances when ticking off the options (no need to exit and restart FF anymore)
- Resistance to cases where the trash is removed outside of BSP2, by recreating it automatically when needed and detecting it is not there.

With that, I hope this should cure all odd cases around the BSP2 trash .. let me know how that goes on your side after you update to the latest version.
