### ISSUE TITLE
Show path AND title + url  on mouse hover above search result

### ISSUE THREAD

**Issue by quantum101** [aaFn/Bookmark-search-plus-2#291]
It would be nice if there was an option to show folder path + title + url. Currently the option is to show either path or title+url

**Comment by peter-kehl** [comment]
Could this be a partial workaround?
1. Options >
   - selected: Advanced click = click on blank -> "Show bookmark", and click on bookmark label -> "Open" in active tab
   - unselected: After "Show Bookmark", leave bookmark tree open by default when closing search pane
2. In a search result, "click on blank" = click left of the favicon of a found bookmark.
3. Notice its folder. Granted, that doesn't show the folder's path. You can
   - keep pressing left arrow until you locate the ancestor of your choice (but that will close/collapse any intermediary folders), or
   - give thumbs up to #297.
5. "Click on blank" on other found bookmarks (as needed).
6. Press ESC to clear the search.

**Comment by aaFn** [comment]
Hello both, I am hesitating on this one, because this is making big and quite unreadable mouse hover "bubbles" ..

**Comment by aaFn** [comment]
Ok, I crossed the Rubicon, and I am trying .. we will see if that is upsetting users or not.

So 2.0.128 is out, and I changed the option from  "On mouse hover above search result, show path to bookmark item **instead of** title + url" to "On mouse hover above search result, show path to bookmark item **in addition** to title + url".

Let me know ..
