### ISSUE TITLE
When starting Firefox, BSP2 is automatically opened in the sidebar

### ISSUE THREAD

**Issue by Ralf800** [aaFn/Bookmark-search-plus-2#312]
Hi, when I start Firefox, BSP2 is automatically opened in the sidebar. Regardless of the settings. But I don't want BSP2 to be opened.
Is there a way to not display BSP2 when Firefox starts?

**Comment by aaFn** [comment]
Hello, this is a Firefox behavior .. it restarts the sidebar which was opened (if any) when it was closed.

**Comment by Ralf800** [comment]
Hello, I know that the sidebar opens if it was open when I closed FF. BSP2 always starts even if I close BSP before exiting FF. If I uninstall BSP2, the sidebar works normally.

I use FF 130.0 (64 bit) and Windows 10 pro 22H2

**Comment by aaFn** [comment]
If you close the BSP2 sidebar before exiting FF, then the BSP2 sidebar doesn't show up when you reopen FF.
(and whatever the state of the sidebar, the add-on is still running in background anyway, because it has to be aware of the changes to bookmarks, but again this has no influence on the sidebar being open or not at start).

**Comment by Ralf800** [comment]
Please watch the video

https://github.com/user-attachments/assets/ec84a8d4-b748-4098-a559-4b5443f8bfd2

**Comment by aaFn** [comment]
Well, this is not something that BSP2 controls, and certainly not something that happens on my side ... so it must be something in your FF, or maybe an option set in your FF instance ?
By the way, what happens if instead of BSP2, you display the native bookmark panel in the sidebar, and repeat the same experience ?

**Comment by Ralf800** [comment]
Well, when I display the native bookmarks panel in the sidebar, BSP2 still loads in the sidbar the next time I launch FF. Always in all variations.
If I deactivate BSP2, I have the normal behavior, as it should be.

**Comment by aaFn** [comment]
Ok, strange, and no idea of why your FF behaves like that. This is not a feature of BSP2, and not happening on my FF, same version than you.
