### ISSUE TITLE
Feature Request: thumbnails

### ISSUE THREAD

**Issue by lewinr** [aaFn/Bookmark-search-plus-2#34]
Hi, this is a big feature request.

I used to use to a firefix extension called "[Viewmarks](https://addons.mozilla.org/en-US/firefox/addon/viewmarks/)" which was great, it basically created thumbnails for each bookmark and allowed you to work with your bookmarks as thumbnails.  I find it much easier to find things visually, so seeing thumbnails of the webpage worked great.  

Here is how it looked:
![image](https://user-images.githubusercontent.com/38337281/38712335-c374dfa4-3e7f-11e8-8f0f-a47e764906bc.png)

Unfortunately this extension is no longer updated and doesnt work with the latest version of Firefox and the author has no plans to update it.

I wonder if you would consider adding a similar functionality.  I know it would be alot of work but I think it will really take your bookmark manager to a new level... :)

Thank you in any case for the great add-in even as it is today....

**Comment by aaFn** [comment]
Indeed, plenty of good things in that old extension ..
- The Trash can idea is a good one for example :-)
- And the thumbnail view would fit well with Android platform for BSP2 .. so far I am not enabling BSP2 on Android because there is no Sidebar on Android FF ..

However, lots of work as you say.

I am flagging this as "for later consideration".
The motivation would be to make BSP2 available on Android, and then a side effect would be to have it also available on Windows/Linux/IOS as an additional mean, in parallel to the sidebar or replacing it for those who prefer that form ..

**Comment by aaFn** [comment]
This is too far away from where BSP2 evolved, and wouldn't fit well with the very high numbers of bookmarks BSP2 is aimed at supporting, in terms of visual display, performance, unsollicited web traffic to capture thumbnails and amount of memory to store those large numbers, so the request is abandonned.

Thank you, aaFn.

**Comment by lewinr** [comment]
😢 thank you anyway
