### ISSUE TITLE
Feature request: Ctrl left click on bookmark opens it in new tab

### ISSUE THREAD

**Issue by chr7** [aaFn/Bookmark-search-plus-2#44]
The following Firefox Quantum feature is missing:
Clicking with the left mouse button on a bookmark while holding down the (left) control key, opens the bookmark in a new tab.

This doesn't work if this plugin is active. Please add this feature.

**Comment by aaFn** [comment]
You are correct, and in fact the alignment should be wider:
- shift + click = currently has special effect of forcing the bookmark opening wherever we click on the line, as per #3, but this is incorrect since in the native bookmark, shift + click opens in a new window .. I should switch to another key then .. I will pick Alt as it appears to have no special effect in native FF bookmarks
- ctrl + click = should open in new tab

Therefore in 2.0.24 I will modify the behavior to:
- `SHIFT + LEFT CLICK` = open bookmark in new window
- `CTRL + LEFT CLICK` = open bookmark in new tab
- `ALT + LEFT CLICK` = forces activation of the bookmark
=> in result window (non advanced mode) will do "Find in tree + open bookmark in current tab".
=> and in bookmarks window, will open the bookmark in current tab wherever we click on the line

**Comment by aaFn** [comment]
Done in 2.0.24, which is out.
