### ISSUE TITLE
Add option for only one favicon for all sites from the same domain

### ISSUE THREAD

**Issue by andreygursky** [aaFn/Bookmark-search-plus-2#51]
Having thousands of bookmarks from the same domain (and the same favicon) makes no sense to download each of them (and even not possible under constrained available bandwidth).

**Comment by aaFn** [comment]
Hello @andreygursky , BSP2 is following the native bookmark sidebar behavior, which is fetching the favicons per page, and not per domain, as ruled in HTML: https://www.w3schools.com/tags/att_link_rel.asp = the "favicon" is "an icon to represent the document".
BSP2 is doing nothing more (and nothing less), and so does not consume more volume than normal bookmark sidebar.

I guess your problem is when the bookmarks are first discovered by BSP2, the load of all favicons is concentrated. So a solution should be an option to slow down that download so as to decrease the instantaneous bandwidth .. counterpart is that it can be very long to get all favicons of course, but that is not a problem, BSP2 is resilient to that and across restarts (if the "Disable favicon fetching" option is not set).

If you absolutely want to have something at domain level, then you need to open the demand to Bugzilla first (https://bugzilla.mozilla.org/) so that FF implements it. When it is implemented, BSP2 will implement it in the same.way.

Let me know what you prefer. Thanks, aaFn.

**Comment by andreygursky** [comment]
> I guess your problem is when the bookmarks are first discovered by BSP2, the load of all favicons is concentrated.

Yes.

> So a solution should be an option to slow down that download so as to decrease the instantaneous bandwidth .. counterpart is that it can be very long to get all favicons of course, but that is not a problem, BSP2 is resilient to that and across restarts (if the "Disable favicon fetching" option is not set).

I fear this wouldn't help me. Though I have no statistic about average html page size in my bookmarks, but for the example https://github.com/aaFn/Bookmark-search-plus-2/issues/49#issuecomment-404893903:

158538 bytes * 58618 (bookmarks) = 9293180484 bytes

Even if I give FF the whole available bandwidth of 64 Kbit/s, only html fetch would last almost 14 days. And this without favicon fetching at all.

> If you absolutely want to have something at domain level, then you need to open the demand to Bugzilla first

If this cannot be implemented in the plugin itself, then perhaps this will be needed. But since there is already an issue about allowing direct access to already available favicon data and it is still open, I'm not sure a request about workaround for that open issue would be resolved faster.

**Comment by aaFn** [comment]
Sure .. now, before you got the "Restore previous session" problem, you already had all favicons downloaded on the same machine, hadn't you ? And that wen well on bandwidth I guess, since it was not noticed.

By the way, average of just the HTML is probably not 158 KB !!

Plus, do not forget that FF is intelligent :-)
It caches things .. so when you access a page and BSP2 gets it also just behind, there is no transfer on the network normally, this should all be in FF cache on disk.

**Comment by andreygursky** [comment]
No they were not downloaded. Only small fracture.

**Comment by andreygursky** [comment]
> BSP2 is following the native bookmark sidebar behavior, which is fetching the favicons per page, and not per domain, as ruled in HTML

> Plus, do not forget that FF is intelligent :-)

Indeed. favicons.sqlite. There is a map from from page_id to icon_id, which can be same for different page_id. So FF doesn't seem to save the same icon more often than necessary.

**Comment by aaFn** [comment]
Yes, probably pretty optimized .. As said on the other thread, would require to split the objects though, so impacting perfs of the add-on ... We are in jabascript, they are in native code .. they can do things we can"t ... :-(

**Comment by andreygursky** [comment]
> We are in jabascript, they are in native code .. they can do things we can"t ... :-(

Yeah. I hoped actually, that FF manages local storage (also for extensions) in sqlite, not in big/huge raw json files!

**Comment by aaFn** [comment]
See #49, some progress .. I will leave that one open to discuss if we need bandwidth throttling or not.

**Comment by aaFn** [comment]
I didn't observe nor get anymore reports of latencies or problems due to large favicon fetching. It seems FF has cured some of the memory hog problems, and also the throttling I implemented now seems to play a good role in making things smooth.

As said above, implementing a "per domain" favicon would add an indirection which I believe would have some counter effect on the display code performance, on which I spent much time to optimize. So for now I am closing that issue as "Wontfix", assuming things are ok, or that at worst people are relying on the "No favicon fetching" option and this is sufficient.

Thank you, aaFn.
