### ISSUE TITLE
Plugin gets stuck loading

### ISSUE THREAD

**Issue by frz-dev** [aaFn/Bookmark-search-plus-2#52]
Since a month or so (most likely since the last update) the addon is just not working anymore. When I open the sidebar it keeps saying "Wait background load..." but nothing happens. I tried on a different computer, and the same applies.

**Comment by aaFn** [comment]
Hello gents, sorry I was on vacations ...
Yes, to accelerate things (#2 and #5), I had to drastically change some things and put them in a background page.
The difficulty is that background page errors are hard to catch, because they most often happen while there is nothing around to log anything, and there's also nothing catching exceptions then ...

I noticed that there was some problems of synchronization at some moment and so implemented that force reload button for that purpose.

However, I suppose I could implement a more intelligent mechanism if I could detect that BSP2 is not loading properly, and force the API reload to try to auto-resolve.

Also, a good way to catch what is happening to the background task and BSP2 in such "stuck loading" situations is to:
```
1. Open the browser console with Ctrl + Shift + J
2. Open a tab with URL "about:addons" or Ctrl + Shift + A
3. Deactivate BSP2
4. Clean the browser console by clicking on the Trashbin icon
5. Re-activate BSP2
6. Select all that is in the browser console from first row to last with the mouse
7. Copy / paste it here  in that issue which I will keep open
8. Also give me the contents of the trace textarea if any.
```

With that, I can usually pinpoint the problem and repair it.

Sorry for the inconveninence, and any details on the errors you get will be much useful to make things more robust, so looking forward whatever you can bring. Thanks, aaFn.

**Comment by progfa** [comment]
I get this:

Load saved state..

background.js:90:5
jsonified save method

background.js:90:5
Error on loading from local storage : TypeError: BN is null background.js:1555:2
lineNumber: 566 background.js:1556:2
fileName:   moz-extension://72990318-6a4a-479b-8a0d-89efbbacf751/sidebar/BookmarkNode.js background.js:1557:2

After some time i get this trace:

Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
Invalid chrome URI: /
The resource at “https://www.google-analytics.com/collect” was blocked because tracking protection is enabled.[Learn More] login
Invalid chrome URI: /
Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
[Show/hide message details.] Log warning: The log 'Services.Common.RESTRequest' is configured to use the preference 'services.common.log.logger.rest.request' - you must adjust the level by setting this preference, not by using the level setter Log.jsm:31
The resource at “https://www.google-analytics.com/collect” was blocked because tracking protection is enabled.[Learn More]

**Comment by aaFn** [comment]
Good, thanks.
It looks like your state save got corrupted some way ... and so couldn't deserialize properly.
I was so far assuming it was always correct, but wrongly.

I am now checking the returned value, and if null because corrupted (so not exploitable), I am forcing a reload of bookmarks from the FF API.

This can be much longer because of https://bugzilla.mozilla.org/show_bug.cgi?id=1396364, but this should always work and then next time the save / reload should be ok, so faster.
this should contribute to making BSP2 more robust to such glitches.

2.0.32 is out with the corection. Let me know if this is going better or if you are still having trouble (and then I will need the same traces following the above method in post number 3, in order to investigate what else lays behind).

Thanks, aaFn.

**Comment by mantheakis** [comment]
Thanks to @seanmcgu22 I also clicked the "Reload from FF API now" option and it fixed the problem.

FWIW I only have this problem with Firefox Developer Edition. The standard Firefox Quantum has not suffered this problem - though I synchronize to the same FF account on both versions.

**Comment by aaFn** [comment]
Ok, glad it helps as this button was made for that :-).

Now, before doing it, when anybody new gets the problem, it would help if you can first execute the following before hitting the button, and post the result here. That will help getting more robust, by allowing me to detect remaining cases leading to that situation and by correcting them or automatically triggering the reload:
```
1. Open the browser console with Ctrl + Shift + J
2. Open a tab with URL "about:addons" or Ctrl + Shift + A
3. Deactivate BSP2 in that tab
4. Clean the browser console by clicking on the Trashbin icon
5. Re-activate BSP2 in the  "about:addons" tab ... it will leave init traces in the browser console
6. Select all that is in the browser console from first row to last with the mouse
7. Copy / paste it here  in that issue which I will keep open
8. Also give me the contents of the trace textarea if any.
```

**Comment by aaFn** [comment]
Good. Thank you for the feedback :-)

**Comment by PackElend** [comment]
the problem still exists in Firefox 62.0 (64-Bit)

**Comment by PackElend** [comment]
16:37:07.907 Load saved state..

background.js:98:5
16:37:08.282 [Mitteilungsdetails anzeigen/ausblenden] XHRGET
https://sync-581-us-west-2.sync.services.mozilla.com/1.5/91199258/info/collections
[HTTP/1.1 200 OK 188ms]
16:37:08.286 jsonified save method

background.js:98:5
16:37:08.329 Error on loading from local storage : TypeError: BN is null background.js:1891:2
16:37:08.330 lineNumber: 594 background.js:1892:2
16:37:08.330 fileName:   moz-extension://2ec2787c-cb3a-4fee-bca1-58225fd5f044/sidebar/BookmarkNode.js background.js:1893:2
16:37:08.484 [Mitteilungsdetails anzeigen/ausblenden] XHRGET
https://sync-581-us-west-2.sync.services.mozilla.com/1.5/91199258/info/configuration
[HTTP/1.1 200 OK 193ms]
16:37:08.697 [Mitteilungsdetails anzeigen/ausblenden] XHRGET
https://sync-581-us-west-2.sync.services.mozilla.com/1.5/91199258/storage/clients?full=1&limit=1000
[HTTP/1.1 200 OK 190ms]
16:37:08.999 [Mitteilungsdetails anzeigen/ausblenden] XHRPOST
https://sync-581-us-west-2.sync.services.mozilla.com/1.5/91199258/storage/tabs?batch=true&commit=true
[HTTP/1.1 200 OK 197ms]
16:37:09.341 [Mitteilungsdetails anzeigen/ausblenden] XHRPOST
https://sync-581-us-west-2.sync.services.mozilla.com/1.5/91199258/storage/addons?batch=true&commit=true
[HTTP/1.1 200 OK 269ms]
16:37:09.740 [Mitteilungsdetails anzeigen/ausblenden] XHRGET
https://webextensions.settings.services.mozilla.com/v1/buckets/default/collections/ext-zHLnakivq6BQ3hIJBEkHCS0sTdTwamXZkwOY0E6dIck/records?_sort=-last_modified
[HTTP/1.1 200 OK 223ms]
16:37:09.740 [Mitteilungsdetails anzeigen/ausblenden] XHRGET
https://webextensions.settings.services.mozilla.com/v1/buckets/default/collections/ext-cpTzeX20qxNrdrjoFSAXH9BfI8BXHtGLzWoDyKWR92A/records?_sort=-last_modified&_since=1535705277104
[HTTP/1.1 200 OK 226ms]
16:37:09.741 [Mitteilungsdetails anzeigen/ausblenden] XHRGET
https://webextensions.settings.services.mozilla.com/v1/buckets/default/collections/ext-Gp2-PohXXC-2P4n_Ja_lpLmOL6WAN98Ls7jO71-_f10/records?_sort=-last_modified&_since=1514640625817
[HTTP/1.1 200 OK 219ms]
16:37:09.742 [Mitteilungsdetails anzeigen/ausblenden] XHRGET
https://webextensions.settings.services.mozilla.com/v1/buckets/default/collections/ext-oQ3djuv7Ck7oJmZWfaAldULm4KU_CzTYHf7gnbuBVNQ/records?_sort=-last_modified
[HTTP/1.1 200 OK 204ms]
16:37:09.743 [Mitteilungsdetails anzeigen/ausblenden] XHRGET
https://webextensions.settings.services.mozilla.com/v1/buckets/default/collections/ext-3c-eT2c85rVL38yy9cE8ecCvbbxLTACc3BEIPgVtDsE/records?_sort=-last_modified&_since=1514566913895
[HTTP/1.1 200 OK 233ms]
16:37:09.743 [Mitteilungsdetails anzeigen/ausblenden] XHRGET
https://webextensions.settings.services.mozilla.com/v1/buckets/default/collections/ext-AyRZPeHcAU2zqLDTV010h6laIcZRhhd89pcaco_ydJs/records?_sort=-last_modified&_since=1536407241876
[HTTP/1.1 200 OK 209ms]
16:37:09.772 [Mitteilungsdetails anzeigen/ausblenden] XHRGET
https://webextensions.settings.services.mozilla.com/v1/buckets/default/collections/ext-jmu2ldrRR6gZX7uI3kUrSyTdyQY0pcTqoV-DiabuNEw/records?_sort=-last_modified&_since=1523562167416
[HTTP/1.1 200 OK 384ms]
16:37:09.783 [Mitteilungsdetails anzeigen/ausblenden] XHRGET
https://webextensions.settings.services.mozilla.com/v1/buckets/default/collections/ext-VJbV5KJZPPgpntt9afAaokRsJcGM5zLgyKXutzG9O9o/records?_sort=-last_modified&_since=1534169131849
[HTTP/1.1 200 OK 371ms]
16:37:10.175 [Mitteilungsdetails anzeigen/ausblenden] XHRPOST
https://webextensions.settings.services.mozilla.com/v1/batch
[HTTP/1.1 507 Insufficient Storage 259ms]

**Comment by aaFn** [comment]
Hello, thanks for the feedback. Again some save corruption it seems.
I added some checks to detect that and force an FF API bookmark tree reload in such case.
It should be out tonight in 2.0.36.

**Comment by PackElend** [comment]
> It should be out tonight in 2.0.36.
great, will check tomorrow then.

off topic question, why don't you integrate the add-in function in Firefox native bookmark side bar and bookmark manager? That would boost the usability of Firefox.

**Comment by aaFn** [comment]
Hello @PackElend , 2.0.36 is out, let me know if the problem disappears or not.

On your side question, it is not possible anymore with Quantum and WenExtensions to do that.
Firefox removed that capability for security purposes, and a lot of very useful extensions have disappeared because of that.
This is why I created that add-on.
Else, I would still be using the original Bookmark Search Plus extension from Alice0775, which was doing exactly what you say.

**Comment by PackElend** [comment]
works like a charme

**Comment by aaFn** [comment]
Good. Thank you for the quick feedback :-)

**Comment by aaFn** [comment]
It's been nearly 3 months now, so I guess we've passed that problem.
Closing .. thank you, aaFn.
