### ISSUE TITLE
Feature request: open bookmark without find in tree in addition

### ISSUE THREAD

**Issue by chr7** [aaFn/Bookmark-search-plus-2#53]
Often I just need so search for a bookmark and have it opened without leaving the current open folder of the bookmark tree - so, it's enough to have the bookmark found in the search results, no need to find it in the tree in addition.

Maybe as an option to specify if clicking on a bookmark in the result list just opens the bookmark or finds it in the tree in addition.

Is it possible to implement such a feature?

**Comment by aaFn** [comment]
Or maybe I could manage to assign that to the Alt key in "Advnaced mode" ...
So complementing #44 with **bold**:

- `SHIFT + LEFT CLICK` = open bookmark in new window
- `CTRL + LEFT CLICK` = open bookmark in new tab
- `ALT + LEFT CLICK` = forces activation of the bookmark
=> in result window - non advanced mode - find in tree + open bookmark in current tab
**=> in result window - advanced mode - open bookmark in current tab only**
=> and in bookmarks window, open the bookmark in current tab wherever we click on the line

How would that sound ?

**Comment by chr7** [comment]
What's not so comfortable with your proposed solution: I would loose the possibility to open the bookmark from the search panel either in a new window or tab.

What about the following: add some option that when enabled doesn't find the bookmark in the tree automatically any longer but adds an entry to the popup menu (right mouse click) that offers to find the bookmark in the tree.

**Comment by aaFn** [comment]
Hello @chr7, I still am not inclined to that path, because:
1. I am trying to limit the number of options
2. This behavior is not aligned with the initial add-on BSP that BSP2 is replacing

I'd rather rely on key modifiers (= savvy users) if possible. Fortunately, ALT is meant to be composed with the other keys, and this is already the case today. So it would allow you to also open the bookmark from the search panel in a new window or new tab:

- In **Simple click** mode ALT would keep its current behavior of forcing the open bookmark in addition to _find in tree_ = no change compared to today
  - If no ALT -> _find in tree_ only, regardless of whether CTRL or SHIFT are pressed or not
  - If ALT alone -> _find in tree_ and _open in current tab_
  - If ALT with CTRL -> _find in tree_ and _open in new tab_
  - If ALT with SHIFT -> _find in tree_ and _open in new window_
- In **Advanced click** mode, it would also force the open bookmark, but inhibit the _find in tree_
  - If no ALT -> depends on where we click on the line (blank or favicon / text - and CTRL and SHIFT only have an effect when clicking on favicon or text)
  - If ALT alone -> _open in current tab_ only (no find)
  - If ALT with CTRL -> _open in new tab_ only (no find)
  - If ALT with SHIFT -> _open in new window_ only (no find)

Therefore, you would get what you want in Advanced mode.

**Comment by chr7** [comment]
What about leaving it up the user to define the keys for the different activities? For example, I already use ALT + SHIFT for another plugin ...

**Comment by aaFn** [comment]
Hello @chr7 , it won't interfere, don't worry .. the key combination goes where the focus is, and the focus is where you click.
So if you have ALT + SHIFT used by another plugin, that plugin never gets it anyway when you click on an object inside BSP2 sidebar. It only gets it when you click on an area used / managed by the other plugin .. and since the sidebar is exclusive, it cannot be mpanaged by something else than BSP2.
Try it today, and you will see :-)

**Comment by aaFn** [comment]
Solved with 2.0.42+
cf. https://github.com/aaFn/Bookmark-search-plus-2/wiki/Mouse-clicks-and-modifiers-summary-table-(as-of-2.0.42-)
Now as soon as a key modifier is pressed when clicking, there is no show/find the bookmark in tree, and things are not moving in that pane.

aaFn.
