### ISSUE TITLE
Disable middle mouse button scroll functionality

### ISSUE THREAD

**Issue by fade2gray** [aaFn/Bookmark-search-plus-2#57]
Hi, is it possible to disable FF's middle mouse button scroll functionality, which gets activated if the mmb is clicked (and can't be dismissed with the ESC key) and scrollbars are present within the bookmarks sidebar (not an issue with FF's default sidebar)?

While I'm aware that I could use either Ctrl+LeftClick or the menu option to open bookmarks in a new tab, trying to untrain muscle memory to avoid using the mmb is proving difficult :)

Thanks

![mousescroll](https://user-images.githubusercontent.com/1332009/46675386-2c365c00-cbd6-11e8-8023-d921cf27b235.png)

**Comment by aaFn** [comment]
Hello @fade2gray , the problem only happens on Windows, and I noticed it since the beginning.
However, the answer to your question is no, I didn't find a way to disable that, sorry.

It looks like this is a system or FF behavior which cannot be overriden on the event, even when trying to prevent all defaults, bubbling up .. etc ... Maybe an FF bug in Windows ? Not such pb on Linux for example.

**Comment by fade2gray** [comment]
Oh well, too bad. Still is a must-have addon though. Thanks

**Comment by aaFn** [comment]
Good news, I eventually found a way how to do it in 2.0.41 .. :-)
So now this issue is solved.
