### ISSUE TITLE
Dragging bookmark to folder: should drop as first child.

### ISSUE THREAD

**Issue by JohnLukeBentley** [aaFn/Bookmark-search-plus-2#61]
When you drag a bookmark from the address bar into a folder the current behaviour OnDrop is to add the bookmark as the last child of the bookmarks within the folder.

I request that this be changed so that it is the first child (or, alternatively, add this as an option). 

Edit: "that" to "the".

**Comment by aaFn** [comment]
Hello @JohnLukeBentley, I will close the issue as BSP2 is already giving the proper way to do it.
Let me know if I am missing something.
Thanks, aaFn.

**Comment by JohnLukeBentley** [comment]
Hello great @aaFn. Sorry I haven't replied earlier...

Thanks to your explanation I now see that it is native FF behaviour for a bookmark dropped onto a folder to go the last child position.

I also see that one can drag a bookmark straight to the first child position (in BSP2 or native).

And on the grounds that you want to be consistent with native behaviour I suppose it is right to default to last position on folder drop.

However, when dragging a bookmark to around the first child position (just underneath a folder) there appears to be a subtle difference:

* BSP2 seems to offer two options: first child of folder; and next sibling of folder; by contrast
* Native seems to only offer one option: first child of folder;

Under BSP2 I can deliberately drop the bookmark at the relevant place and have it go either to first child of folder or next sibling of folder. However, there's two problems with this:

1. This is inconsistent with native. If being consistent with native behaviour matters then perhaps it matters here too; and
2. While I can do it, I find it too fiddly. I'd rather not have the "next sibling of folder" area (well it's a thin line) under the folder so that "first child of folder" more reliably engages.

What do you think?

**Comment by aaFn** [comment]
Hello @JohnLukeBentley , the "next sibling of folder" area exists in the native bookmark sidebar when the folder is closed. It doesn't exist when it is open. This is way to complex code to handle as this becomes non uniform between bookmark items, depending on whether they are folder or not, and whether they are open or not.

So BSP2 presents a slight difference here indeed, by being uniform =
- each item, whatever its type, has an insert position before and an insert position after.
- and the after of previous item is not necessarily the before of next item ... that all depends on the position in the tree, so removing one of them depending on very specific conditions is just a complexity I do not want to add in the code at this stage, for a very minimal UI change that nearly nobody will notice. As for those who notice, half will like it because this is logical, and half won't like it .. not really going to lead anywhere, so the effort is not worth it.

Hope that explains :-)

**Comment by JohnLukeBentley** [comment]
Response to https://github.com/aaFn/Bookmark-search-plus-2/issues/61#issuecomment-447504980

Thanks, that helps push my understanding along. However, ...

>  the "next sibling of folder" area exists in the native bookmark sidebar when the folder is closed. It doesn't exist when it is open.

... that's not right and perhaps, after explaining, I can better make my case (and/or you could present a better retort) ...

## The drop area between "last child of folder" and "next sibling of folder"

For the native bar the drop area between "last child of folder" and "next sibling of folder"area exists even for open folders:

* Open a folder (having all bookmark children; or all folder children ... it doesn't matter).
* Drag a bookmark from the address bar until the blue drag line is between the last child of the folder and the next sibling of the folder. Keep the left mouse button pressed ...
* ... With the left mouse button still pressed drag your cursor so that the tip of the arrow:
  + Is slightly **above** the blue drag line. Drop here. Your bookmark becomes the last child of the folder; or
  + Is slightly **below** the blue drag line. Drop here. Your bookmark becomes the next sibling of the folder.

However, in the native bar, there's no visual indication that differentiates a change in target location ("last child of the folder" V " next sibling of the folder )."

In BSP2 you seem to have this work in the same, with one exceptional superior behaviour. Your blue drag line will visibly change to indicate a change in target location. That's a good thing.

I don't think you should make any change here.

## The drop area over a (highlighted) folder

Native and BSP2 also seem to behave identically if you drag a bookmark and hover over a (closed or open) folder. The folder's background will change to blue. If you now drop the bookmark it will reliably end up in the "last child of the folder".

This also works whether the folder is open or closed.

I don't think you should make any change here.

## The drop area between folder and first child.

When you drop a bookmark in the area between the folder and the first child (necessarily when the folder is open) then native and BSP2 behave differently:
* Native: the bookmark is always dropped to the first child position;
* BSP2: the bookmark is dropped either to the first child position or the folder's next sibling position, depending on subtle cursor position.

My proposition is with respect to this drop area only: to make BSP2 behave like the native bar.

To implement this no complex algorithm is needed. Indeed you'd probably have to make your code simpler (I'm not suggesting this sort of coding change is necessarily trivial ... all small coding changes can take some time). That is, as far I can see the only issue is what sort of design one wants (or is best).

**Comment by aaFn** [comment]
> ... With the left mouse button still pressed drag your cursor so that the tip of the arrow:
>     Is slightly above the blue drag line. Drop here. Your bookmark becomes the last child of the folder; or
>     Is slightly below the blue drag line. Drop here. Your bookmark becomes the next sibling of the folder.
> 
Thanks for that, I didn't notice ...! And indeed that's not obvious at all :-)

Now on the last one, but coupled with this one: the visual change in line you see between the last child and the folder next sibling is marking something subtly different from what you describe:
- this is marking either the next sibling of the last child, as you say, or the **previous** sibling of the folder next sibling
- so not the folder next sibling. That one is marked by the line just after the folder itself, which is causing what you say.

This is so because the objects on the UI, for speed and optimization reasons, are all the same.
So there is no object (like the folder) encompassing all others (its children). The visual line for "next" is always physically just after it on the GUI.

Changing that is not so easy. In fact, the closest to what you want would be to disable the "next sibling" insert line of a folder, as I was saying in a previous post. Still something asking for code under very specific conditions and may be perf impacting ... as this would ask for checking if there is or not a next sibling to the folder, if it is open or not .. etc ..

By the way, to illustrate, try something in the native toolbar:
- Create a folder so that it is the very last item in the bookmark pane
- Add a bookmark inside it
- Open the folder
- Create another bookmark item just before the folder (or anywhere else, but just before is easier ..)
- Try to drag and move that new bookmark as next sibling of the folder

You will never succeed, **unless the folder is closed** which is really asking for specific code .. (or let me know, on my side I didn't find how to do that).

In BSP2, this is easy to do = drop it just below the folder item, when the insert line mark is showing that this is the folder we're using as reference for insert, and o it will be the folder next sibling .. and the item will move at the very end, just after the folder, whether it is open or closed ..

If I suppress that one, the function is lost .. so I prefer for now to keep it, even if this is slightly inconsistent, as you rightfully point out, with the native sidebar.
