### ISSUE TITLE
Mouse clicks and modifiers summary table (as of 2.0.46 ): show action on different mouse clicks

### ISSUE THREAD

**Issue by chr7** [aaFn/Bookmark-search-plus-2#76]
I would like to ask for the following improvement.

Some actions described in the "Mouse clicks and modifiers summary table (as of 2.0.46 )" are not consistent. For example, if the result pane is in advance mode and I click a bookmark (image or text)  in the result pane then the bookmark is shown in the bookmark pane too but not if I hold down Shift or Ctrl in addition.

Thus I suggest to make the "show" action available on different mouse clicks, i.e. if left mouse button is used then there is no "Show" action and when middle mouse button is clicked then you get the "Show"action in addition.

**Comment by aaFn** [comment]
Yes, correct, and to not show while you click on the image or text, press on Alt at the same time.

That was a logic asked for elsewhere (#53), to be able to do actions on the search pane results and manipulating objects without moving the current zone visible in the bookmark pane.

For example, a right click on the result shows the context menu and allows to do a cut, so that it can be pasted by another right click in the bookmark pane .. and if right click in results executes show, this breaks the use case.

No simple answer for all => use cases and practicality are the drivers, to the detriment of "consistency" some times indeed.

**Comment by aaFn** [comment]
Closing as already available through other means.
Thank you, AaFn.
