### ISSUE TITLE
.ffavicon in Firefox 65+

### ISSUE THREAD

**Issue by WernerFP** [aaFn/Bookmark-search-plus-2#83]
The problem occurs in Firefox for Linux. I guess it's the same in Windows and MacOs.

In Firefox 65 (cur. Developer) and 66 (cur. Nightly) the folder icon (`.ffavicon`) is displayed improperly. Curiously there (and only there) is a 3D inset-border around the icon:

![ffolder](https://user-images.githubusercontent.com/22373662/51427998-9e1f3800-1bfe-11e9-8455-05854431fb90.png)

A possible workaround is to set the frame to zero size and stretch the background-image to 16px.
```
.ffavicon {
  display: inline-block;
  width: 0;
  height: 0;
  padding: 8px;
  vertical-align: text-bottom;
  background-image: url("/icons/folder.png");
}
```

**Comment by aaFn** [comment]
Hello @WernerFP , strange. And you say this happens starting with FF65 ?
Ok I'll get it and look at it.
folder.png is one of the favicons having transparency, there might be something inherited on the <img> HTML object with FF65 that would need to be removed .. Hopefully the Inspector will allowme to find that faulty attribute ..

**Comment by aaFn** [comment]
Hello @WernerFP, well I checked, but FF65 seems completely broken.
Some times it displays web pages correctly and sometimes it does strange things like this one:

![image2](https://user-images.githubusercontent.com/36155054/51869560-3204a880-2351-11e9-9014-5827ba10dbc6.png)

On the same computer with FF64, all is right.
Obviously something is wrong with the betas ...

**Comment by aaFn** [comment]
Result is that with a transparent image, the insets are not showing at all ...

It might be that FF65+ does not like `img` elements without any src="..." attributes anymore.
Let me know what you think ...

**Comment by WernerFP** [comment]
I think you're right. The absent `scr` attribute is interpreted differently: [fficon_without-scr.html](https://gist.github.com/WernerFP/e319f9f246fd0c99c5dd15d29d4b2b21)

Result: FF 64 | FF 65/66 | Chromium/Chrome

![ffavicon_img-without-scr](https://user-images.githubusercontent.com/22373662/51910611-04ab0f80-23d0-11e9-970c-b19986b0d188.png)

In my opinion it is OK to use an `img` element as placeholder for a CSS `background-image` (without stretching to 16px). A `div` container would probably be the cleaner method. The result is the same for both: [fficon_img-versus-div.html](https://gist.github.com/WernerFP/fcd40f30bae02ad49371d777cfda7a84)

**Comment by aaFn** [comment]
Very good .. thanks for the suggestion, I take it :-)

As a matter of fact, I must use `img` elements with the `src=` attribute for all fetched URI's, because this is the only reliable way to really find the size of fetched image URI's, after loading them (`img.onload` event) .. and then to start a conversion process to 16x16 for space saving and speed of display.

However, for the case of folders, and also for the special one of "no favicon" favicon when the `Disable favicon fetching..` option is set, I do not need any conversion since I am using an internal PNG file which is as I need to be.

When creating objects for display, I am using "templates" with the Node.cloneNode() method https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode to speed things up.
In the case of folders and nofavicon, I simply copied the code I am using for the other cases without much thinking about it ... but no need to use `img` there .. so changing it for `div` as you say, and this works everywhere (and I agree it is cleaner, I do not need all the `img` stuff at all for all these objects).

Will be in 2.0.52 .. thank you again

**Comment by aaFn** [comment]
Ok, FF65 is out tonight .. so I just released 2.0.52 ... let me know if all is ok on your side. It appears to be on mine.

Thank you, aaFn.

**Comment by WernerFP** [comment]
Everything's fine.
Just in time with the rolling out of FF65, that's perfect!

**Comment by aaFn** [comment]
:-)

Thanks again for the heads up, and for the suggestion.
Closing the issue now.
