### ISSUE TITLE
I don't like this add-on.

### ISSUE THREAD

**Issue by jerkstore369** [aaFn/Bookmark-search-plus-2#87]
Hi, I just found this add-on and I don't really like it. In Alice0775's implementation (go/show parent folder), he had it so that you can just add a column in the library to see the parent folder. Can't you just do that? First of all, I don't like that I have to load a link just to just to see the parent folder. Sometimes I just want to organize my bookmarks, I have to load each one? That's ridiculous. Isn't there a way to just implement everything in the library? If not, can't you just create an API for that?

**Comment by aaFn** [comment]
Hello @jerkstore369,

   to start with, a bit of history:
alice0775 had 3 XUL extensions, named:
- Bookmark Search Plus, extending the sidebar to allow showing where is a bookmark from a search, and to manipulate bookmarks directly in the sidebar
- Show Parent Folder, which was adding the column you mention in the Bookmark Library
- Go Parent Folder, which was adding, if my memory serves me well, a context menu action to find the parent folder of a bookmark, in the sidebar or in the Bookmark Library

BSP2 is to be the follow up of the first one, in the FF post-Quantum world, and is trying to help on the other two, but hits FF API limitations which prevent it from really doing them also.

----------------------------------------------

On your first point (adding to Library), this is not anymore possible with WebExtensions.
Alice0775 was using XUL technology to do the work, but Firefox removed XUL since version 57 (Quantum).

The new API given by FF is much more limited and does not allow anything to be done, at least today, inside the bookmarks library.

I was using a lot alice0775 extensions, and in particular Bookmark Search Plus. When FF stopped supporting that, I decided to write the follow up of it, asking alice0775 if that was ok -> https://github.com/alice0775/userChrome.js/issues/37
.. no answer to date, but I was too much missing the simple and basic function of searching bookmarks and finding in which folder they lie, that I proceeded and developed this add-on, mimicking as much as I could the initial Bookmark Search Plus extension.

Cf. https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on
and
 https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Comparison_with_XUL_XPCOM_extensions
about Mozilla not allowing XUL and direct manipulation of FF UI anymore ...

----------------------------------------------

Now to your second point (load a bookmark to see where it is):

You are not at all obliged to load a bookmark to see where it is .. not sure what makes you say that.

There are 3 ways to locate where a bookmark is, and none of them forces you to load the bookmark:

1. In simple mode (which is the default in the Options), simply type the title or URL of the bookmark you are looking for in the search box of the sidebar, and you get the list of matching bookmarks in the search pane which opens just below.
Then, click on any of them and it will show in the bookmark pane .. That does not "load them" as you say.
From there, you can drag and drop, within the bookmark pane or from the search pane, to move bookmarks around from one place to another.
2. In advanced mode (you have to set it in the Options), you have to click on the blank part on left or right of the bookmark to **only** show it.
If you click on the Favicon or bookmark text itself, indeed it gets loaded .. this is how the initial BSP was behaving, so I kept it for advanced people like me who were used to it .. but I made it a non default option to avoid that normal people have to adapt to that complexity.
3. In the top (menu bar) Bookmarks menu, showing all your bookmark (and in your Personal Toolbar, showing some of them), I have added a contextual menu entry `BSP2 Path to bookmark item`, appearing when you right click on any bookmark or folder.
If you extend that submenu, you will see the path to the bookmark or folder in textual form, like the column which was added in the Library in its time.
Unfortunately, that does not work in the Library today, FF doesn't permit that .. I hope one day they will.
This is the closest I could do until today to "Go/Show Parent Folder".

I hope this is clearer. Let me know if you have any question left,

Thank you, aaFn.

**Comment by aaFn** [comment]
Closing as I believe all questions / demand for information are answered.
Please reopen if not.

Thank you, aaFn.
